// Messages for the forecast procedures or the QuartzAPI

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fcfsapi/crud.proto

package fcfsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	MakeDefault   bool                   `protobuf:"varint,3,opt,name=make_default,json=makeDefault,proto3" json:"make_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_fcfsapi_crud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{0}
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateModelRequest) GetMakeDefault() bool {
	if x != nil {
		return x.MakeDefault
	}
	return false
}

type CreateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       int32                  `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_fcfsapi_crud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModelResponse) GetModelId() int32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type Forecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       int32                  `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	LocationId    int32                  `protobuf:"varint,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,3,opt,name=energy_source,json=energySource,proto3,enum=fcfsapi.EnergySource" json:"energy_source,omitempty"`
	InitTimeUtc   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=init_time_utc,json=initTimeUtc,proto3" json:"init_time_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	mi := &file_fcfsapi_crud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{2}
}

func (x *Forecast) GetModelId() int32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *Forecast) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *Forecast) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *Forecast) GetInitTimeUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.InitTimeUtc
	}
	return nil
}

type CreateForecastRequest struct {
	state                     protoimpl.MessageState                            `protogen:"open.v1"`
	Forecast                  *Forecast                                         `protobuf:"bytes,1,opt,name=forecast,proto3" json:"forecast,omitempty"`
	PredictedGenerationValues []*CreateForecastRequest_PredictedGenerationValue `protobuf:"bytes,2,rep,name=predicted_generation_values,json=predictedGenerationValues,proto3" json:"predicted_generation_values,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateForecastRequest) Reset() {
	*x = CreateForecastRequest{}
	mi := &file_fcfsapi_crud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastRequest) ProtoMessage() {}

func (x *CreateForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastRequest.ProtoReflect.Descriptor instead.
func (*CreateForecastRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{3}
}

func (x *CreateForecastRequest) GetForecast() *Forecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *CreateForecastRequest) GetPredictedGenerationValues() []*CreateForecastRequest_PredictedGenerationValue {
	if x != nil {
		return x.PredictedGenerationValues
	}
	return nil
}

type CreateForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForecastId    int64                  `protobuf:"varint,1,opt,name=forecast_id,json=forecastId,proto3" json:"forecast_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForecastResponse) Reset() {
	*x = CreateForecastResponse{}
	mi := &file_fcfsapi_crud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastResponse) ProtoMessage() {}

func (x *CreateForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastResponse.ProtoReflect.Descriptor instead.
func (*CreateForecastResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{4}
}

func (x *CreateForecastResponse) GetForecastId() int64 {
	if x != nil {
		return x.ForecastId
	}
	return 0
}

type CreateSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=fcfsapi.EnergySource" json:"energy_source,omitempty"`
	Latitude      float32                `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CapacityKw    int64                  `protobuf:"varint,5,opt,name=capacity_kw,json=capacityKw,proto3" json:"capacity_kw,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSiteRequest) Reset() {
	*x = CreateSiteRequest{}
	mi := &file_fcfsapi_crud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteRequest) ProtoMessage() {}

func (x *CreateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteRequest.ProtoReflect.Descriptor instead.
func (*CreateSiteRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSiteRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *CreateSiteRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateSiteRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateSiteRequest) GetCapacityKw() int64 {
	if x != nil {
		return x.CapacityKw
	}
	return 0
}

func (x *CreateSiteRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CreateGspRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=fcfsapi.EnergySource" json:"energy_source,omitempty"`
	Geometry      string                 `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
	CapacityMw    int64                  `protobuf:"varint,4,opt,name=capacity_mw,json=capacityMw,proto3" json:"capacity_mw,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGspRequest) Reset() {
	*x = CreateGspRequest{}
	mi := &file_fcfsapi_crud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGspRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGspRequest) ProtoMessage() {}

func (x *CreateGspRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGspRequest.ProtoReflect.Descriptor instead.
func (*CreateGspRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGspRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGspRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *CreateGspRequest) GetGeometry() string {
	if x != nil {
		return x.Geometry
	}
	return ""
}

func (x *CreateGspRequest) GetCapacityMw() int64 {
	if x != nil {
		return x.CapacityMw
	}
	return 0
}

func (x *CreateGspRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CreateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationResponse) Reset() {
	*x = CreateLocationResponse{}
	mi := &file_fcfsapi_crud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationResponse) ProtoMessage() {}

func (x *CreateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationResponse.ProtoReflect.Descriptor instead.
func (*CreateLocationResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLocationResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=fcfsapi.EnergySource" json:"energy_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_fcfsapi_crud_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{8}
}

func (x *GetLocationRequest) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetLocationRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

type GetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float32                `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CapacityKw    int64                  `protobuf:"varint,5,opt,name=capacity_kw,json=capacityKw,proto3" json:"capacity_kw,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_fcfsapi_crud_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{9}
}

func (x *GetLocationResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetLocationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLocationResponse) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetLocationResponse) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetLocationResponse) GetCapacityKw() int64 {
	if x != nil {
		return x.CapacityKw
	}
	return 0
}

func (x *GetLocationResponse) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type GetLocationsAsGeoJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationIds   []int32                `protobuf:"varint,1,rep,packed,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	Unsimplified  bool                   `protobuf:"varint,2,opt,name=unsimplified,proto3" json:"unsimplified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationsAsGeoJSONRequest) Reset() {
	*x = GetLocationsAsGeoJSONRequest{}
	mi := &file_fcfsapi_crud_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationsAsGeoJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationsAsGeoJSONRequest) ProtoMessage() {}

func (x *GetLocationsAsGeoJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationsAsGeoJSONRequest.ProtoReflect.Descriptor instead.
func (*GetLocationsAsGeoJSONRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{10}
}

func (x *GetLocationsAsGeoJSONRequest) GetLocationIds() []int32 {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *GetLocationsAsGeoJSONRequest) GetUnsimplified() bool {
	if x != nil {
		return x.Unsimplified
	}
	return false
}

type GetLocationsAsGeoJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geojson       string                 `protobuf:"bytes,1,opt,name=geojson,proto3" json:"geojson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationsAsGeoJSONResponse) Reset() {
	*x = GetLocationsAsGeoJSONResponse{}
	mi := &file_fcfsapi_crud_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationsAsGeoJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationsAsGeoJSONResponse) ProtoMessage() {}

func (x *GetLocationsAsGeoJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationsAsGeoJSONResponse.ProtoReflect.Descriptor instead.
func (*GetLocationsAsGeoJSONResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{11}
}

func (x *GetLocationsAsGeoJSONResponse) GetGeojson() string {
	if x != nil {
		return x.Geojson
	}
	return ""
}

type CreateObservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=fcfsapi.EnergySource" json:"energy_source,omitempty"`
	ObserverName  string                 `protobuf:"bytes,3,opt,name=observer_name,json=observerName,proto3" json:"observer_name,omitempty"`
	Yields        []*Yield               `protobuf:"bytes,4,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObservationsRequest) Reset() {
	*x = CreateObservationsRequest{}
	mi := &file_fcfsapi_crud_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObservationsRequest) ProtoMessage() {}

func (x *CreateObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObservationsRequest.ProtoReflect.Descriptor instead.
func (*CreateObservationsRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{12}
}

func (x *CreateObservationsRequest) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *CreateObservationsRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *CreateObservationsRequest) GetObserverName() string {
	if x != nil {
		return x.ObserverName
	}
	return ""
}

func (x *CreateObservationsRequest) GetYields() []*Yield {
	if x != nil {
		return x.Yields
	}
	return nil
}

type CreateObservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObservationsResponse) Reset() {
	*x = CreateObservationsResponse{}
	mi := &file_fcfsapi_crud_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObservationsResponse) ProtoMessage() {}

func (x *CreateObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObservationsResponse.ProtoReflect.Descriptor instead.
func (*CreateObservationsResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{13}
}

type CreateObserverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObserverRequest) Reset() {
	*x = CreateObserverRequest{}
	mi := &file_fcfsapi_crud_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObserverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObserverRequest) ProtoMessage() {}

func (x *CreateObserverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObserverRequest.ProtoReflect.Descriptor instead.
func (*CreateObserverRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{14}
}

func (x *CreateObserverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateObserverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObserverId    int32                  `protobuf:"varint,1,opt,name=observer_id,json=observerId,proto3" json:"observer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObserverResponse) Reset() {
	*x = CreateObserverResponse{}
	mi := &file_fcfsapi_crud_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObserverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObserverResponse) ProtoMessage() {}

func (x *CreateObserverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObserverResponse.ProtoReflect.Descriptor instead.
func (*CreateObserverResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{15}
}

func (x *CreateObserverResponse) GetObserverId() int32 {
	if x != nil {
		return x.ObserverId
	}
	return 0
}

type CreateForecastRequest_PredictedGenerationValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HorizonMins   int32                  `protobuf:"varint,1,opt,name=horizon_mins,json=horizonMins,proto3" json:"horizon_mins,omitempty"`
	P50Pct        float32                `protobuf:"fixed32,2,opt,name=p50_pct,json=p50Pct,proto3" json:"p50_pct,omitempty"`
	P10Pct        float32                `protobuf:"fixed32,3,opt,name=p10_pct,json=p10Pct,proto3" json:"p10_pct,omitempty"`
	P90Pct        float32                `protobuf:"fixed32,4,opt,name=p90_pct,json=p90Pct,proto3" json:"p90_pct,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForecastRequest_PredictedGenerationValue) Reset() {
	*x = CreateForecastRequest_PredictedGenerationValue{}
	mi := &file_fcfsapi_crud_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastRequest_PredictedGenerationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastRequest_PredictedGenerationValue) ProtoMessage() {}

func (x *CreateForecastRequest_PredictedGenerationValue) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_crud_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastRequest_PredictedGenerationValue.ProtoReflect.Descriptor instead.
func (*CreateForecastRequest_PredictedGenerationValue) Descriptor() ([]byte, []int) {
	return file_fcfsapi_crud_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetHorizonMins() int32 {
	if x != nil {
		return x.HorizonMins
	}
	return 0
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetP50Pct() float32 {
	if x != nil {
		return x.P50Pct
	}
	return 0
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetP10Pct() float32 {
	if x != nil {
		return x.P10Pct
	}
	return 0
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetP90Pct() float32 {
	if x != nil {
		return x.P90Pct
	}
	return 0
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_fcfsapi_crud_proto protoreflect.FileDescriptor

const file_fcfsapi_crud_proto_rawDesc = "" +
	"\n" +
	"\x12fcfsapi/crud.proto\x12\afcfsapi\x1a\x14fcfsapi/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\x12CreateModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fmake_default\x18\x03 \x01(\bR\vmakeDefault\"0\n" +
	"\x13CreateModelResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x05R\amodelId\"\xc2\x01\n" +
	"\bForecast\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x05R\amodelId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\x05R\n" +
	"locationId\x12:\n" +
	"\renergy_source\x18\x03 \x01(\x0e2\x15.fcfsapi.EnergySourceR\fenergySource\x12>\n" +
	"\rinit_time_utc\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vinitTimeUtc\"\xe6\x02\n" +
	"\x15CreateForecastRequest\x12-\n" +
	"\bforecast\x18\x01 \x01(\v2\x11.fcfsapi.ForecastR\bforecast\x12w\n" +
	"\x1bpredicted_generation_values\x18\x02 \x03(\v27.fcfsapi.CreateForecastRequest.PredictedGenerationValueR\x19predictedGenerationValues\x1a\xa4\x01\n" +
	"\x18PredictedGenerationValue\x12!\n" +
	"\fhorizon_mins\x18\x01 \x01(\x05R\vhorizonMins\x12\x17\n" +
	"\ap50_pct\x18\x02 \x01(\x02R\x06p50Pct\x12\x17\n" +
	"\ap10_pct\x18\x03 \x01(\x02R\x06p10Pct\x12\x17\n" +
	"\ap90_pct\x18\x04 \x01(\x02R\x06p90Pct\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"9\n" +
	"\x16CreateForecastResponse\x12\x1f\n" +
	"\vforecast_id\x18\x01 \x01(\x03R\n" +
	"forecastId\"\xda\x01\n" +
	"\x11CreateSiteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x15.fcfsapi.EnergySourceR\fenergySource\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x02R\tlongitude\x12\x1f\n" +
	"\vcapacity_kw\x18\x05 \x01(\x03R\n" +
	"capacityKw\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"\xbb\x01\n" +
	"\x10CreateGspRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x15.fcfsapi.EnergySourceR\fenergySource\x12\x1a\n" +
	"\bgeometry\x18\x03 \x01(\tR\bgeometry\x12\x1f\n" +
	"\vcapacity_mw\x18\x04 \x01(\x03R\n" +
	"capacityMw\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"9\n" +
	"\x16CreateLocationResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\"q\n" +
	"\x12GetLocationRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12:\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x15.fcfsapi.EnergySourceR\fenergySource\"\xc1\x01\n" +
	"\x13GetLocationResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x02R\tlongitude\x12\x1f\n" +
	"\vcapacity_kw\x18\x05 \x01(\x03R\n" +
	"capacityKw\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"e\n" +
	"\x1cGetLocationsAsGeoJSONRequest\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\x05R\vlocationIds\x12\"\n" +
	"\funsimplified\x18\x02 \x01(\bR\funsimplified\"9\n" +
	"\x1dGetLocationsAsGeoJSONResponse\x12\x18\n" +
	"\ageojson\x18\x01 \x01(\tR\ageojson\"\xc5\x01\n" +
	"\x19CreateObservationsRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12:\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x15.fcfsapi.EnergySourceR\fenergySource\x12#\n" +
	"\robserver_name\x18\x03 \x01(\tR\fobserverName\x12&\n" +
	"\x06yields\x18\x04 \x03(\v2\x0e.fcfsapi.YieldR\x06yields\"\x1c\n" +
	"\x1aCreateObservationsResponse\"+\n" +
	"\x15CreateObserverRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\x16CreateObserverResponse\x12\x1f\n" +
	"\vobserver_id\x18\x01 \x01(\x05R\n" +
	"observerIdB@Z>github.com/devsjc/fcfs/api/src/internal/models/fcfsapi;fcfsapib\x06proto3"

var (
	file_fcfsapi_crud_proto_rawDescOnce sync.Once
	file_fcfsapi_crud_proto_rawDescData []byte
)

func file_fcfsapi_crud_proto_rawDescGZIP() []byte {
	file_fcfsapi_crud_proto_rawDescOnce.Do(func() {
		file_fcfsapi_crud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fcfsapi_crud_proto_rawDesc), len(file_fcfsapi_crud_proto_rawDesc)))
	})
	return file_fcfsapi_crud_proto_rawDescData
}

var file_fcfsapi_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_fcfsapi_crud_proto_goTypes = []any{
	(*CreateModelRequest)(nil),                             // 0: fcfsapi.CreateModelRequest
	(*CreateModelResponse)(nil),                            // 1: fcfsapi.CreateModelResponse
	(*Forecast)(nil),                                       // 2: fcfsapi.Forecast
	(*CreateForecastRequest)(nil),                          // 3: fcfsapi.CreateForecastRequest
	(*CreateForecastResponse)(nil),                         // 4: fcfsapi.CreateForecastResponse
	(*CreateSiteRequest)(nil),                              // 5: fcfsapi.CreateSiteRequest
	(*CreateGspRequest)(nil),                               // 6: fcfsapi.CreateGspRequest
	(*CreateLocationResponse)(nil),                         // 7: fcfsapi.CreateLocationResponse
	(*GetLocationRequest)(nil),                             // 8: fcfsapi.GetLocationRequest
	(*GetLocationResponse)(nil),                            // 9: fcfsapi.GetLocationResponse
	(*GetLocationsAsGeoJSONRequest)(nil),                   // 10: fcfsapi.GetLocationsAsGeoJSONRequest
	(*GetLocationsAsGeoJSONResponse)(nil),                  // 11: fcfsapi.GetLocationsAsGeoJSONResponse
	(*CreateObservationsRequest)(nil),                      // 12: fcfsapi.CreateObservationsRequest
	(*CreateObservationsResponse)(nil),                     // 13: fcfsapi.CreateObservationsResponse
	(*CreateObserverRequest)(nil),                          // 14: fcfsapi.CreateObserverRequest
	(*CreateObserverResponse)(nil),                         // 15: fcfsapi.CreateObserverResponse
	(*CreateForecastRequest_PredictedGenerationValue)(nil), // 16: fcfsapi.CreateForecastRequest.PredictedGenerationValue
	(EnergySource)(0),                                      // 17: fcfsapi.EnergySource
	(*timestamppb.Timestamp)(nil),                          // 18: google.protobuf.Timestamp
	(*Yield)(nil),                                          // 19: fcfsapi.Yield
}
var file_fcfsapi_crud_proto_depIdxs = []int32{
	17, // 0: fcfsapi.Forecast.energy_source:type_name -> fcfsapi.EnergySource
	18, // 1: fcfsapi.Forecast.init_time_utc:type_name -> google.protobuf.Timestamp
	2,  // 2: fcfsapi.CreateForecastRequest.forecast:type_name -> fcfsapi.Forecast
	16, // 3: fcfsapi.CreateForecastRequest.predicted_generation_values:type_name -> fcfsapi.CreateForecastRequest.PredictedGenerationValue
	17, // 4: fcfsapi.CreateSiteRequest.energy_source:type_name -> fcfsapi.EnergySource
	17, // 5: fcfsapi.CreateGspRequest.energy_source:type_name -> fcfsapi.EnergySource
	17, // 6: fcfsapi.GetLocationRequest.energy_source:type_name -> fcfsapi.EnergySource
	17, // 7: fcfsapi.CreateObservationsRequest.energy_source:type_name -> fcfsapi.EnergySource
	19, // 8: fcfsapi.CreateObservationsRequest.yields:type_name -> fcfsapi.Yield
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_fcfsapi_crud_proto_init() }
func file_fcfsapi_crud_proto_init() {
	if File_fcfsapi_crud_proto != nil {
		return
	}
	file_fcfsapi_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fcfsapi_crud_proto_rawDesc), len(file_fcfsapi_crud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fcfsapi_crud_proto_goTypes,
		DependencyIndexes: file_fcfsapi_crud_proto_depIdxs,
		MessageInfos:      file_fcfsapi_crud_proto_msgTypes,
	}.Build()
	File_fcfsapi_crud_proto = out.File
	file_fcfsapi_crud_proto_goTypes = nil
	file_fcfsapi_crud_proto_depIdxs = nil
}
