// Messages for the QuartzUI procedures of the QuartzAPI service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fcfsapi/quartzui.proto

package fcfsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- GetPredictedTimeseries --------------------------------------------------------
type GetPredictedTimeseriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationIds   []int32                `protobuf:"varint,1,rep,packed,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedTimeseriesRequest) Reset() {
	*x = GetPredictedTimeseriesRequest{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedTimeseriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedTimeseriesRequest) ProtoMessage() {}

func (x *GetPredictedTimeseriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedTimeseriesRequest.ProtoReflect.Descriptor instead.
func (*GetPredictedTimeseriesRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{0}
}

func (x *GetPredictedTimeseriesRequest) GetLocationIds() []int32 {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

type GetPredictedTimeseriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Yields        []*PredictedYield      `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedTimeseriesResponse) Reset() {
	*x = GetPredictedTimeseriesResponse{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedTimeseriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedTimeseriesResponse) ProtoMessage() {}

func (x *GetPredictedTimeseriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedTimeseriesResponse.ProtoReflect.Descriptor instead.
func (*GetPredictedTimeseriesResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{1}
}

func (x *GetPredictedTimeseriesResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetPredictedTimeseriesResponse) GetYields() []*PredictedYield {
	if x != nil {
		return x.Yields
	}
	return nil
}

type PredictedYield struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	YieldKw       int32                      `protobuf:"varint,1,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	TimestampUnix int64                      `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Uncertainty   *PredictedYieldUncertainty `protobuf:"bytes,3,opt,name=uncertainty,proto3" json:"uncertainty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictedYield) Reset() {
	*x = PredictedYield{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictedYield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedYield) ProtoMessage() {}

func (x *PredictedYield) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedYield.ProtoReflect.Descriptor instead.
func (*PredictedYield) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{2}
}

func (x *PredictedYield) GetYieldKw() int32 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

func (x *PredictedYield) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *PredictedYield) GetUncertainty() *PredictedYieldUncertainty {
	if x != nil {
		return x.Uncertainty
	}
	return nil
}

type PredictedYieldUncertainty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LowerKw       int32                  `protobuf:"varint,1,opt,name=lower_kw,json=lowerKw,proto3" json:"lower_kw,omitempty"`
	UpperKw       int32                  `protobuf:"varint,2,opt,name=upper_kw,json=upperKw,proto3" json:"upper_kw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictedYieldUncertainty) Reset() {
	*x = PredictedYieldUncertainty{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictedYieldUncertainty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedYieldUncertainty) ProtoMessage() {}

func (x *PredictedYieldUncertainty) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedYieldUncertainty.ProtoReflect.Descriptor instead.
func (*PredictedYieldUncertainty) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{3}
}

func (x *PredictedYieldUncertainty) GetLowerKw() int32 {
	if x != nil {
		return x.LowerKw
	}
	return 0
}

func (x *PredictedYieldUncertainty) GetUpperKw() int32 {
	if x != nil {
		return x.UpperKw
	}
	return 0
}

// --- GetActualTimeseries -----------------------------------------------------------
type GetActualTimeseriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationIds   []string               `protobuf:"bytes,1,rep,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActualTimeseriesRequest) Reset() {
	*x = GetActualTimeseriesRequest{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActualTimeseriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActualTimeseriesRequest) ProtoMessage() {}

func (x *GetActualTimeseriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActualTimeseriesRequest.ProtoReflect.Descriptor instead.
func (*GetActualTimeseriesRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{4}
}

func (x *GetActualTimeseriesRequest) GetLocationIds() []string {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

type GetActualTimeseriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Yields        []*ActualYield         `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActualTimeseriesResponse) Reset() {
	*x = GetActualTimeseriesResponse{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActualTimeseriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActualTimeseriesResponse) ProtoMessage() {}

func (x *GetActualTimeseriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActualTimeseriesResponse.ProtoReflect.Descriptor instead.
func (*GetActualTimeseriesResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{5}
}

func (x *GetActualTimeseriesResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetActualTimeseriesResponse) GetYields() []*ActualYield {
	if x != nil {
		return x.Yields
	}
	return nil
}

type ActualYield struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YieldKw       int32                  `protobuf:"varint,1,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualYield) Reset() {
	*x = ActualYield{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualYield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualYield) ProtoMessage() {}

func (x *ActualYield) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualYield.ProtoReflect.Descriptor instead.
func (*ActualYield) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{6}
}

func (x *ActualYield) GetYieldKw() int32 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

func (x *ActualYield) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

// --- GetPredictedCrossSection ------------------------------------------------------
type GetPredictedCrossSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationIds   []int32                `protobuf:"varint,1,rep,packed,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedCrossSectionRequest) Reset() {
	*x = GetPredictedCrossSectionRequest{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedCrossSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedCrossSectionRequest) ProtoMessage() {}

func (x *GetPredictedCrossSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedCrossSectionRequest.ProtoReflect.Descriptor instead.
func (*GetPredictedCrossSectionRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{7}
}

func (x *GetPredictedCrossSectionRequest) GetLocationIds() []int32 {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *GetPredictedCrossSectionRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type GetPredictedCrossSectionResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	TimestampUnix int64                       `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Yields        []*PredictedYieldAtLocation `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedCrossSectionResponse) Reset() {
	*x = GetPredictedCrossSectionResponse{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedCrossSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedCrossSectionResponse) ProtoMessage() {}

func (x *GetPredictedCrossSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedCrossSectionResponse.ProtoReflect.Descriptor instead.
func (*GetPredictedCrossSectionResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{8}
}

func (x *GetPredictedCrossSectionResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *GetPredictedCrossSectionResponse) GetYields() []*PredictedYieldAtLocation {
	if x != nil {
		return x.Yields
	}
	return nil
}

type PredictedYieldAtLocation struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	LocationId    int32                      `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	YieldKw       int32                      `protobuf:"varint,2,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	Uncertainty   *PredictedYieldUncertainty `protobuf:"bytes,3,opt,name=uncertainty,proto3" json:"uncertainty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictedYieldAtLocation) Reset() {
	*x = PredictedYieldAtLocation{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictedYieldAtLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedYieldAtLocation) ProtoMessage() {}

func (x *PredictedYieldAtLocation) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedYieldAtLocation.ProtoReflect.Descriptor instead.
func (*PredictedYieldAtLocation) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{9}
}

func (x *PredictedYieldAtLocation) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *PredictedYieldAtLocation) GetYieldKw() int32 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

func (x *PredictedYieldAtLocation) GetUncertainty() *PredictedYieldUncertainty {
	if x != nil {
		return x.Uncertainty
	}
	return nil
}

// --- GetActualCrossSection ---------------------------------------------------------
type GetActualCrossSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationIds   []int32                `protobuf:"varint,1,rep,packed,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActualCrossSectionRequest) Reset() {
	*x = GetActualCrossSectionRequest{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActualCrossSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActualCrossSectionRequest) ProtoMessage() {}

func (x *GetActualCrossSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActualCrossSectionRequest.ProtoReflect.Descriptor instead.
func (*GetActualCrossSectionRequest) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{10}
}

func (x *GetActualCrossSectionRequest) GetLocationIds() []int32 {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *GetActualCrossSectionRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type GetActualCrossSectionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TimestampUnix int64                    `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Yields        []*ActualYieldAtLocation `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActualCrossSectionResponse) Reset() {
	*x = GetActualCrossSectionResponse{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActualCrossSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActualCrossSectionResponse) ProtoMessage() {}

func (x *GetActualCrossSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActualCrossSectionResponse.ProtoReflect.Descriptor instead.
func (*GetActualCrossSectionResponse) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{11}
}

func (x *GetActualCrossSectionResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *GetActualCrossSectionResponse) GetYields() []*ActualYieldAtLocation {
	if x != nil {
		return x.Yields
	}
	return nil
}

type ActualYieldAtLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	YieldKw       int32                  `protobuf:"varint,2,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualYieldAtLocation) Reset() {
	*x = ActualYieldAtLocation{}
	mi := &file_fcfsapi_quartzui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualYieldAtLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualYieldAtLocation) ProtoMessage() {}

func (x *ActualYieldAtLocation) ProtoReflect() protoreflect.Message {
	mi := &file_fcfsapi_quartzui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualYieldAtLocation.ProtoReflect.Descriptor instead.
func (*ActualYieldAtLocation) Descriptor() ([]byte, []int) {
	return file_fcfsapi_quartzui_proto_rawDescGZIP(), []int{12}
}

func (x *ActualYieldAtLocation) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *ActualYieldAtLocation) GetYieldKw() int32 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

var File_fcfsapi_quartzui_proto protoreflect.FileDescriptor

const file_fcfsapi_quartzui_proto_rawDesc = "" +
	"\n" +
	"\x16fcfsapi/quartzui.proto\x12\afcfsapi\"B\n" +
	"\x1dGetPredictedTimeseriesRequest\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\x05R\vlocationIds\"r\n" +
	"\x1eGetPredictedTimeseriesResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12/\n" +
	"\x06yields\x18\x02 \x03(\v2\x17.fcfsapi.PredictedYieldR\x06yields\"\x98\x01\n" +
	"\x0ePredictedYield\x12\x19\n" +
	"\byield_kw\x18\x01 \x01(\x05R\ayieldKw\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\x12D\n" +
	"\vuncertainty\x18\x03 \x01(\v2\".fcfsapi.PredictedYieldUncertaintyR\vuncertainty\"Q\n" +
	"\x19PredictedYieldUncertainty\x12\x19\n" +
	"\blower_kw\x18\x01 \x01(\x05R\alowerKw\x12\x19\n" +
	"\bupper_kw\x18\x02 \x01(\x05R\aupperKw\"?\n" +
	"\x1aGetActualTimeseriesRequest\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\tR\vlocationIds\"l\n" +
	"\x1bGetActualTimeseriesResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12,\n" +
	"\x06yields\x18\x02 \x03(\v2\x14.fcfsapi.ActualYieldR\x06yields\"O\n" +
	"\vActualYield\x12\x19\n" +
	"\byield_kw\x18\x01 \x01(\x05R\ayieldKw\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\"k\n" +
	"\x1fGetPredictedCrossSectionRequest\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\x05R\vlocationIds\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\"\x84\x01\n" +
	" GetPredictedCrossSectionResponse\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x129\n" +
	"\x06yields\x18\x02 \x03(\v2!.fcfsapi.PredictedYieldAtLocationR\x06yields\"\x9c\x01\n" +
	"\x18PredictedYieldAtLocation\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12\x19\n" +
	"\byield_kw\x18\x02 \x01(\x05R\ayieldKw\x12D\n" +
	"\vuncertainty\x18\x03 \x01(\v2\".fcfsapi.PredictedYieldUncertaintyR\vuncertainty\"h\n" +
	"\x1cGetActualCrossSectionRequest\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\x05R\vlocationIds\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\"~\n" +
	"\x1dGetActualCrossSectionResponse\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x126\n" +
	"\x06yields\x18\x02 \x03(\v2\x1e.fcfsapi.ActualYieldAtLocationR\x06yields\"S\n" +
	"\x15ActualYieldAtLocation\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12\x19\n" +
	"\byield_kw\x18\x02 \x01(\x05R\ayieldKwB@Z>github.com/devsjc/fcfs/api/src/internal/models/fcfsapi;fcfsapib\x06proto3"

var (
	file_fcfsapi_quartzui_proto_rawDescOnce sync.Once
	file_fcfsapi_quartzui_proto_rawDescData []byte
)

func file_fcfsapi_quartzui_proto_rawDescGZIP() []byte {
	file_fcfsapi_quartzui_proto_rawDescOnce.Do(func() {
		file_fcfsapi_quartzui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fcfsapi_quartzui_proto_rawDesc), len(file_fcfsapi_quartzui_proto_rawDesc)))
	})
	return file_fcfsapi_quartzui_proto_rawDescData
}

var file_fcfsapi_quartzui_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_fcfsapi_quartzui_proto_goTypes = []any{
	(*GetPredictedTimeseriesRequest)(nil),    // 0: fcfsapi.GetPredictedTimeseriesRequest
	(*GetPredictedTimeseriesResponse)(nil),   // 1: fcfsapi.GetPredictedTimeseriesResponse
	(*PredictedYield)(nil),                   // 2: fcfsapi.PredictedYield
	(*PredictedYieldUncertainty)(nil),        // 3: fcfsapi.PredictedYieldUncertainty
	(*GetActualTimeseriesRequest)(nil),       // 4: fcfsapi.GetActualTimeseriesRequest
	(*GetActualTimeseriesResponse)(nil),      // 5: fcfsapi.GetActualTimeseriesResponse
	(*ActualYield)(nil),                      // 6: fcfsapi.ActualYield
	(*GetPredictedCrossSectionRequest)(nil),  // 7: fcfsapi.GetPredictedCrossSectionRequest
	(*GetPredictedCrossSectionResponse)(nil), // 8: fcfsapi.GetPredictedCrossSectionResponse
	(*PredictedYieldAtLocation)(nil),         // 9: fcfsapi.PredictedYieldAtLocation
	(*GetActualCrossSectionRequest)(nil),     // 10: fcfsapi.GetActualCrossSectionRequest
	(*GetActualCrossSectionResponse)(nil),    // 11: fcfsapi.GetActualCrossSectionResponse
	(*ActualYieldAtLocation)(nil),            // 12: fcfsapi.ActualYieldAtLocation
}
var file_fcfsapi_quartzui_proto_depIdxs = []int32{
	2,  // 0: fcfsapi.GetPredictedTimeseriesResponse.yields:type_name -> fcfsapi.PredictedYield
	3,  // 1: fcfsapi.PredictedYield.uncertainty:type_name -> fcfsapi.PredictedYieldUncertainty
	6,  // 2: fcfsapi.GetActualTimeseriesResponse.yields:type_name -> fcfsapi.ActualYield
	9,  // 3: fcfsapi.GetPredictedCrossSectionResponse.yields:type_name -> fcfsapi.PredictedYieldAtLocation
	3,  // 4: fcfsapi.PredictedYieldAtLocation.uncertainty:type_name -> fcfsapi.PredictedYieldUncertainty
	12, // 5: fcfsapi.GetActualCrossSectionResponse.yields:type_name -> fcfsapi.ActualYieldAtLocation
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_fcfsapi_quartzui_proto_init() }
func file_fcfsapi_quartzui_proto_init() {
	if File_fcfsapi_quartzui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fcfsapi_quartzui_proto_rawDesc), len(file_fcfsapi_quartzui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fcfsapi_quartzui_proto_goTypes,
		DependencyIndexes: file_fcfsapi_quartzui_proto_depIdxs,
		MessageInfos:      file_fcfsapi_quartzui_proto_msgTypes,
	}.Build()
	File_fcfsapi_quartzui_proto = out.File
	file_fcfsapi_quartzui_proto_goTypes = nil
	file_fcfsapi_quartzui_proto_depIdxs = nil
}
