// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: fcfsapi/service.proto

package fcfsapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuartzAPI_GetPredictedTimeseries_FullMethodName       = "/fcfsapi.QuartzAPI/GetPredictedTimeseries"
	QuartzAPI_GetPredictedTimeseriesDeltas_FullMethodName = "/fcfsapi.QuartzAPI/GetPredictedTimeseriesDeltas"
	QuartzAPI_GetPredictedCrossSection_FullMethodName     = "/fcfsapi.QuartzAPI/GetPredictedCrossSection"
	QuartzAPI_GetObservedTimeseries_FullMethodName        = "/fcfsapi.QuartzAPI/GetObservedTimeseries"
	QuartzAPI_GetLatestForecast_FullMethodName            = "/fcfsapi.QuartzAPI/GetLatestForecast"
	QuartzAPI_GetLocationsAsGeoJSON_FullMethodName        = "/fcfsapi.QuartzAPI/GetLocationsAsGeoJSON"
	QuartzAPI_CreateSolarSite_FullMethodName              = "/fcfsapi.QuartzAPI/CreateSolarSite"
	QuartzAPI_CreateSolarGsp_FullMethodName               = "/fcfsapi.QuartzAPI/CreateSolarGsp"
	QuartzAPI_GetSolarLocation_FullMethodName             = "/fcfsapi.QuartzAPI/GetSolarLocation"
	QuartzAPI_CreateModel_FullMethodName                  = "/fcfsapi.QuartzAPI/CreateModel"
	QuartzAPI_CreateSolarForecast_FullMethodName          = "/fcfsapi.QuartzAPI/CreateSolarForecast"
)

// QuartzAPIClient is the client API for QuartzAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuartzAPIClient interface {
	GetPredictedTimeseries(ctx context.Context, in *GetPredictedTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPredictedTimeseriesResponse], error)
	GetPredictedTimeseriesDeltas(ctx context.Context, in *GetPredictedTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPredictedTimeseriesDeltasResponse], error)
	GetPredictedCrossSection(ctx context.Context, in *GetPredictedCrossSectionRequest, opts ...grpc.CallOption) (*GetPredictedCrossSectionResponse, error)
	GetObservedTimeseries(ctx context.Context, in *GetObservedTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObservedTimeseriesResponse], error)
	GetLatestForecast(ctx context.Context, in *GetLatestForecastRequest, opts ...grpc.CallOption) (*GetLatestForecastResponse, error)
	GetLocationsAsGeoJSON(ctx context.Context, in *GetLocationsAsGeoJSONRequest, opts ...grpc.CallOption) (*GetLocationsAsGeoJSONResponse, error)
	CreateSolarSite(ctx context.Context, in *CreateSiteRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error)
	CreateSolarGsp(ctx context.Context, in *CreateGspRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error)
	GetSolarLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*GetLocationResponse, error)
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error)
	CreateSolarForecast(ctx context.Context, in *CreateForecastRequest, opts ...grpc.CallOption) (*CreateForecastResponse, error)
}

type quartzAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewQuartzAPIClient(cc grpc.ClientConnInterface) QuartzAPIClient {
	return &quartzAPIClient{cc}
}

func (c *quartzAPIClient) GetPredictedTimeseries(ctx context.Context, in *GetPredictedTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPredictedTimeseriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuartzAPI_ServiceDesc.Streams[0], QuartzAPI_GetPredictedTimeseries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPredictedTimeseriesRequest, GetPredictedTimeseriesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetPredictedTimeseriesClient = grpc.ServerStreamingClient[GetPredictedTimeseriesResponse]

func (c *quartzAPIClient) GetPredictedTimeseriesDeltas(ctx context.Context, in *GetPredictedTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPredictedTimeseriesDeltasResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuartzAPI_ServiceDesc.Streams[1], QuartzAPI_GetPredictedTimeseriesDeltas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPredictedTimeseriesRequest, GetPredictedTimeseriesDeltasResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetPredictedTimeseriesDeltasClient = grpc.ServerStreamingClient[GetPredictedTimeseriesDeltasResponse]

func (c *quartzAPIClient) GetPredictedCrossSection(ctx context.Context, in *GetPredictedCrossSectionRequest, opts ...grpc.CallOption) (*GetPredictedCrossSectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPredictedCrossSectionResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_GetPredictedCrossSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) GetObservedTimeseries(ctx context.Context, in *GetObservedTimeseriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObservedTimeseriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuartzAPI_ServiceDesc.Streams[2], QuartzAPI_GetObservedTimeseries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetObservedTimeseriesRequest, GetObservedTimeseriesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetObservedTimeseriesClient = grpc.ServerStreamingClient[GetObservedTimeseriesResponse]

func (c *quartzAPIClient) GetLatestForecast(ctx context.Context, in *GetLatestForecastRequest, opts ...grpc.CallOption) (*GetLatestForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestForecastResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_GetLatestForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) GetLocationsAsGeoJSON(ctx context.Context, in *GetLocationsAsGeoJSONRequest, opts ...grpc.CallOption) (*GetLocationsAsGeoJSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocationsAsGeoJSONResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_GetLocationsAsGeoJSON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) CreateSolarSite(ctx context.Context, in *CreateSiteRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLocationResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_CreateSolarSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) CreateSolarGsp(ctx context.Context, in *CreateGspRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLocationResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_CreateSolarGsp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) GetSolarLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*GetLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocationResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_GetSolarLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzAPIClient) CreateSolarForecast(ctx context.Context, in *CreateForecastRequest, opts ...grpc.CallOption) (*CreateForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateForecastResponse)
	err := c.cc.Invoke(ctx, QuartzAPI_CreateSolarForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuartzAPIServer is the server API for QuartzAPI service.
// All implementations should embed UnimplementedQuartzAPIServer
// for forward compatibility.
type QuartzAPIServer interface {
	GetPredictedTimeseries(*GetPredictedTimeseriesRequest, grpc.ServerStreamingServer[GetPredictedTimeseriesResponse]) error
	GetPredictedTimeseriesDeltas(*GetPredictedTimeseriesRequest, grpc.ServerStreamingServer[GetPredictedTimeseriesDeltasResponse]) error
	GetPredictedCrossSection(context.Context, *GetPredictedCrossSectionRequest) (*GetPredictedCrossSectionResponse, error)
	GetObservedTimeseries(*GetObservedTimeseriesRequest, grpc.ServerStreamingServer[GetObservedTimeseriesResponse]) error
	GetLatestForecast(context.Context, *GetLatestForecastRequest) (*GetLatestForecastResponse, error)
	GetLocationsAsGeoJSON(context.Context, *GetLocationsAsGeoJSONRequest) (*GetLocationsAsGeoJSONResponse, error)
	CreateSolarSite(context.Context, *CreateSiteRequest) (*CreateLocationResponse, error)
	CreateSolarGsp(context.Context, *CreateGspRequest) (*CreateLocationResponse, error)
	GetSolarLocation(context.Context, *GetLocationRequest) (*GetLocationResponse, error)
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error)
	CreateSolarForecast(context.Context, *CreateForecastRequest) (*CreateForecastResponse, error)
}

// UnimplementedQuartzAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuartzAPIServer struct{}

func (UnimplementedQuartzAPIServer) GetPredictedTimeseries(*GetPredictedTimeseriesRequest, grpc.ServerStreamingServer[GetPredictedTimeseriesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetPredictedTimeseries not implemented")
}
func (UnimplementedQuartzAPIServer) GetPredictedTimeseriesDeltas(*GetPredictedTimeseriesRequest, grpc.ServerStreamingServer[GetPredictedTimeseriesDeltasResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetPredictedTimeseriesDeltas not implemented")
}
func (UnimplementedQuartzAPIServer) GetPredictedCrossSection(context.Context, *GetPredictedCrossSectionRequest) (*GetPredictedCrossSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredictedCrossSection not implemented")
}
func (UnimplementedQuartzAPIServer) GetObservedTimeseries(*GetObservedTimeseriesRequest, grpc.ServerStreamingServer[GetObservedTimeseriesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetObservedTimeseries not implemented")
}
func (UnimplementedQuartzAPIServer) GetLatestForecast(context.Context, *GetLatestForecastRequest) (*GetLatestForecastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestForecast not implemented")
}
func (UnimplementedQuartzAPIServer) GetLocationsAsGeoJSON(context.Context, *GetLocationsAsGeoJSONRequest) (*GetLocationsAsGeoJSONResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocationsAsGeoJSON not implemented")
}
func (UnimplementedQuartzAPIServer) CreateSolarSite(context.Context, *CreateSiteRequest) (*CreateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSolarSite not implemented")
}
func (UnimplementedQuartzAPIServer) CreateSolarGsp(context.Context, *CreateGspRequest) (*CreateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSolarGsp not implemented")
}
func (UnimplementedQuartzAPIServer) GetSolarLocation(context.Context, *GetLocationRequest) (*GetLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSolarLocation not implemented")
}
func (UnimplementedQuartzAPIServer) CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedQuartzAPIServer) CreateSolarForecast(context.Context, *CreateForecastRequest) (*CreateForecastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSolarForecast not implemented")
}
func (UnimplementedQuartzAPIServer) testEmbeddedByValue() {}

// UnsafeQuartzAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuartzAPIServer will
// result in compilation errors.
type UnsafeQuartzAPIServer interface {
	mustEmbedUnimplementedQuartzAPIServer()
}

func RegisterQuartzAPIServer(s grpc.ServiceRegistrar, srv QuartzAPIServer) {
	// If the following call pancis, it indicates UnimplementedQuartzAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuartzAPI_ServiceDesc, srv)
}

func _QuartzAPI_GetPredictedTimeseries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPredictedTimeseriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuartzAPIServer).GetPredictedTimeseries(m, &grpc.GenericServerStream[GetPredictedTimeseriesRequest, GetPredictedTimeseriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetPredictedTimeseriesServer = grpc.ServerStreamingServer[GetPredictedTimeseriesResponse]

func _QuartzAPI_GetPredictedTimeseriesDeltas_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPredictedTimeseriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuartzAPIServer).GetPredictedTimeseriesDeltas(m, &grpc.GenericServerStream[GetPredictedTimeseriesRequest, GetPredictedTimeseriesDeltasResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetPredictedTimeseriesDeltasServer = grpc.ServerStreamingServer[GetPredictedTimeseriesDeltasResponse]

func _QuartzAPI_GetPredictedCrossSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPredictedCrossSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).GetPredictedCrossSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_GetPredictedCrossSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).GetPredictedCrossSection(ctx, req.(*GetPredictedCrossSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_GetObservedTimeseries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObservedTimeseriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuartzAPIServer).GetObservedTimeseries(m, &grpc.GenericServerStream[GetObservedTimeseriesRequest, GetObservedTimeseriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuartzAPI_GetObservedTimeseriesServer = grpc.ServerStreamingServer[GetObservedTimeseriesResponse]

func _QuartzAPI_GetLatestForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).GetLatestForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_GetLatestForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).GetLatestForecast(ctx, req.(*GetLatestForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_GetLocationsAsGeoJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationsAsGeoJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).GetLocationsAsGeoJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_GetLocationsAsGeoJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).GetLocationsAsGeoJSON(ctx, req.(*GetLocationsAsGeoJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_CreateSolarSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).CreateSolarSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_CreateSolarSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).CreateSolarSite(ctx, req.(*CreateSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_CreateSolarGsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGspRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).CreateSolarGsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_CreateSolarGsp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).CreateSolarGsp(ctx, req.(*CreateGspRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_GetSolarLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).GetSolarLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_GetSolarLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).GetSolarLocation(ctx, req.(*GetLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzAPI_CreateSolarForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzAPIServer).CreateSolarForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzAPI_CreateSolarForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzAPIServer).CreateSolarForecast(ctx, req.(*CreateForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuartzAPI_ServiceDesc is the grpc.ServiceDesc for QuartzAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuartzAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fcfsapi.QuartzAPI",
	HandlerType: (*QuartzAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPredictedCrossSection",
			Handler:    _QuartzAPI_GetPredictedCrossSection_Handler,
		},
		{
			MethodName: "GetLatestForecast",
			Handler:    _QuartzAPI_GetLatestForecast_Handler,
		},
		{
			MethodName: "GetLocationsAsGeoJSON",
			Handler:    _QuartzAPI_GetLocationsAsGeoJSON_Handler,
		},
		{
			MethodName: "CreateSolarSite",
			Handler:    _QuartzAPI_CreateSolarSite_Handler,
		},
		{
			MethodName: "CreateSolarGsp",
			Handler:    _QuartzAPI_CreateSolarGsp_Handler,
		},
		{
			MethodName: "GetSolarLocation",
			Handler:    _QuartzAPI_GetSolarLocation_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _QuartzAPI_CreateModel_Handler,
		},
		{
			MethodName: "CreateSolarForecast",
			Handler:    _QuartzAPI_CreateSolarForecast_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPredictedTimeseries",
			Handler:       _QuartzAPI_GetPredictedTimeseries_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPredictedTimeseriesDeltas",
			Handler:       _QuartzAPI_GetPredictedTimeseriesDeltas_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetObservedTimeseries",
			Handler:       _QuartzAPI_GetObservedTimeseries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fcfsapi/service.proto",
}
