FROM node:22-alpine AS build-deps

WORKDIR /app
COPY package.json .

RUN npm install

FROM build-deps AS build

ENV PATH=/app/node_modules/.bin:$PATH
COPY . .

RUN npm run build

FROM nginx:1.25.4-alpine3.18

COPY <<-EOF /etc/nginx/conf.d/default.conf
server {
    listen 5173;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }
}
EOF

COPY --from=build /app/dist /var/www/html/

EXPOSE 5173
ENTRYPOINT ["nginx", "-g", "daemon off;"]

