FROM node:22-alpine AS build-static
WORKDIR /app

COPY package.json package-lock.json .
RUN npm install

COPY . .
RUN npm run build

FROM busybox:1.37

RUN adduser -D app
USER app
WORKDIR /home/app

COPY --from=build-static /app/dist .

CMD ["busybox", "httpd", "-f", "-v", "-p", "5173"]

