FROM node:22-alpine AS build-deps

WORKDIR /app
COPY package.json .

RUN npm install

FROM build-deps AS build

ENV PATH=/app/node_modules/.bin:$PATH
COPY . .

RUN npm run build

FROM busybox:latest AS app
COPY --from=build /app/dist .

EXPOSE 5173
ENTRYPOINT ["httpd", "-f", "-v", "-p", "5173"]

