version: '3'

tasks:
  install:
    desc: "Install dependencies using npm"
    cmds:
      - npm install
  run:
    desc: "Run vite server"
    cmds:
      - npm run dev
  download-uk-map:
    desc: "Create uk map .pmtiles file"
    aliases: ["uk-map"]
    cmds:
      - pmtiles extract https://build.protomaps.com/20231023.pmtiles public/uk.pmtiles --bbox=-11.0,49.8,2.5,59.5 --maxzoom=6
  create-gsp-map:
    desc: "Create uk GSP map .pmtiles file"
    aliases: ["uk-gsp"]
    cmds:
      - curl -o gsp-regions-osgb.json https://storage.googleapis.com/dx-national-grid/national-grid/resources/08534dae-5408-4e31-8639-b579c8f1c50b/gsp_regions_20220314.geojson
      - ogr2ogr gsp-regions.json -t_srs "EPSG:4326" gsp-regions-osgb.json
      - rm gsp-regions-osgb.json 
      - tippecanoe --output=public/uk-gsp.pmtiles gsp-regions.json --clip-bounding-box=-11.0,49.8,2.5,59.5 --maximum-zoom=6 --force
      - rm gsp-regions.json


