version: '3'

tasks:
  install:
    desc: "Install dependencies using npm"
    cmds:
      - npm install
  run:
    desc: "Run vite server"
    cmds:
      - npm run dev
  download-uk-map:
    desc: "Create fully populated UK  map as a .pmtiles file"
    aliases: ["uk-map"]
    cmds:
      - pmtiles extract https://build.protomaps.com/20231023.pmtiles public/uk.pmtiles --bbox=-11.0,49.8,2.5,59.5 --maxzoom=6
  create-gsp-map:
    desc: "Create uk GSP feature map .pmtiles file"
    preconditions:
      - sh: command -v ogr2ogr
        msg: "Requires ogr2ogr binary on path. Run `conda install gdal` or see https://gdal.org/download.html"
      - sh: command -v tippecanoe
        msg: "Requires tippecanoe binary on path. Run `brew install tippecanoe` or see https://github.com/mapbox/tippecanoe#installation"
      - sh: command -v mapshaper
        msg: "Requires mapshaper binary on path. Run `npm install -g mapshaper`"
    aliases: ["uk-gsp"]
    cmds:
      - curl -o gsp-regions-osgb.json https://storage.googleapis.com/dx-national-grid/national-grid/resources/08534dae-5408-4e31-8639-b579c8f1c50b/gsp_regions_20220314.geojson
      - ogr2ogr gsp-regions.json -t_srs "EPSG:4326" gsp-regions-osgb.json
      - rm gsp-regions-osgb.json 
      - tippecanoe --output=public/uk-gsp.pmtiles gsp-regions.json --clip-bounding-box=-11.0,49.8,2.5,59.5 --maximum-zoom=8 --force
      - mapshaper gsp-regions.json -simplify dp 3% keep-shapes -o format=geojson public/gsp-regions-lowpoly.json 
      - rm gsp-regions.json
  download-simple-uk-map:
    desc: "Create simplified UK map, with only a few features"
    preconditions:
      - sh: command -v osmium
        msg: "Requires osmium-tools binary on path. Run `brew install osmium-tools` or see https://osmcode.org/osmium-tool"
    aliases: ["uk-roads"]
    cmds:
      - curl -o united-kingdom.osm.pbf https://download.geofabrik.de/europe/united-kingdom-latest.osm.pbf
      - osmium tags-filter united-kingdom.osm.pbf w/highway w/natural=water w/waterway=river w/water w/road -o united-kingdom-filtered.osm.pbf
      - docker run -v $(pwd):$(pwd) chrissi2812/tilemaker --input $(pwd)/united-kingdom-filtered.osm.pbf --output $(pwd)/united-kingdom-filtered.mbtiles
      - pmtiles convert united-kingdom-filtered.mbtiles uk-filtered.pmtiles



