networks:
  fcfs-net:
    driver: bridge

services:

  envoy-proxy:
    container_name: envoy-proxy
    ports:
      - "80:80"
      - "8088:8088"
    image: envoyproxy/envoy-distroless:v1.28-latest
    volumes:
      - ./frontend/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - fcfs-net

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Containerfile
    ports:
      - "50051:50051"
    image: api:local
    networks:
      - fcfs-net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "5713:5713"
    image: frontend:local
    networks:
      - fcfs-net


