networks:
  fcfs-net:
    driver: bridge

services:

  envoy-proxy:
    container_name: envoy-proxy
    ports:
      - "80:80"
      - "8088:8088"
    image: envoyproxy/envoy-distroless:v1.28-latest
    volumes:
      - ./frontend/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on: ["api"]
    networks:
      - fcfs-net

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Containerfile
    ports:
      - "50051:50051"
    image: api:local
    networks:
      - fcfs-net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "5713:5713"
    image: frontend:local
    environment:
      - GRPCWEB_URL=http://envoy-proxy:8088
    depends_on: ["envoy-proxy"]
    networks:
      - fcfs-net

  database:
    container_name: database
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - fcfs-net


