/*
Schema and tables to handle observed generation data.

Observations of generation data is usually measured by providers of inverters,
which are required in many sources of renewable energy to convert power from DC to AC.
Partnerships with these providers provide access to the data in order to
test the accuracy of predictions.
*/

-- +goose Up
-- +goose StatementBegin

CREATE SCHEMA obs;
COMMENT ON SCHEMA obs IS 'Data for observed generation';


/*- Lookups -----------------------------------------------------------------------------------*/

CREATE TABLE obs.power_units (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit TEXT NOT NULL
        CHECK ( unit IN ('W', 'kW', 'MW', 'GW', 'TW') and LENGTH(unit) <= 2),
    PRIMARY KEY (id)
);
COMMENT ON TABLE obs.power_units IS 'Lookup table for power units.';
COMMENT ON COLUMN obs.power_units.id IS 'Unique identifier for the unit';
COMMENT ON COLUMN obs.power_units.unit IS 'Representation of the unit';
INSERT INTO obs.power_units (id, unit) VALUES (0, 'W');
INSERT INTO obs.power_units (unit) VALUES ('kW'),('MW'),('GW'),('TW');


/*- Tables ----------------------------------------------------------------------------------*/

CREATE TABLE obs.observations (
    id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    location_id INT NOT NULL
        REFERENCES loc.locations(id),
    time_utc TIMESTAMP NOT NULL
        CHECK ( time_utc <= CURRENT_TIMESTAMP ),
    generation SMALLINT NOT NULL
        CHECK ( generation >= 0 ),
    generation_units SMALLINT NOT NULL
        REFERENCES obs.power_units(id),
    PRIMARY KEY (id),
    UNIQUE (location_id, time_utc)
);
COMMENT ON TABLE obs.observations IS 'Observed generation data.';
COMMENT ON COLUMN obs.observations.id IS 'Unique identifier for the observation.';
COMMENT ON COLUMN obs.observations.location_id IS 'Location of the observed generation.';
COMMENT ON COLUMN obs.observations.time_utc IS 'Time of the observation in UTC.';
COMMENT ON COLUMN obs.observations.generation IS 'Observed generation value.';
COMMENT ON COLUMN obs.observations.generation_units IS 'Units of the observed generation.';

-- +goose StatementEnd

