// Common messages for the Quartz API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ocf/dp/dp.messages.proto

package dp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnergySource int32

const (
	EnergySource_ENERGY_SOURCE_UNSPECIFIED EnergySource = 0
	EnergySource_ENERGY_SOURCE_SOLAR       EnergySource = 1
	EnergySource_ENERGY_SOURCE_WIND        EnergySource = 2
)

// Enum value maps for EnergySource.
var (
	EnergySource_name = map[int32]string{
		0: "ENERGY_SOURCE_UNSPECIFIED",
		1: "ENERGY_SOURCE_SOLAR",
		2: "ENERGY_SOURCE_WIND",
	}
	EnergySource_value = map[string]int32{
		"ENERGY_SOURCE_UNSPECIFIED": 0,
		"ENERGY_SOURCE_SOLAR":       1,
		"ENERGY_SOURCE_WIND":        2,
	}
)

func (x EnergySource) Enum() *EnergySource {
	p := new(EnergySource)
	*p = x
	return p
}

func (x EnergySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnergySource) Descriptor() protoreflect.EnumDescriptor {
	return file_ocf_dp_dp_messages_proto_enumTypes[0].Descriptor()
}

func (EnergySource) Type() protoreflect.EnumType {
	return &file_ocf_dp_dp_messages_proto_enumTypes[0]
}

func (x EnergySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnergySource.Descriptor instead.
func (EnergySource) EnumDescriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{0}
}

type Yield struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YieldKw       int64                  `protobuf:"varint,1,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Yield) Reset() {
	*x = Yield{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yield) ProtoMessage() {}

func (x *Yield) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yield.ProtoReflect.Descriptor instead.
func (*Yield) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Yield) GetYieldKw() int64 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

func (x *Yield) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type YieldPrediction struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	YieldKw       int64                        `protobuf:"varint,1,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	TimestampUnix int64                        `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Uncertainty   *YieldPrediction_Uncertainty `protobuf:"bytes,3,opt,name=uncertainty,proto3" json:"uncertainty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YieldPrediction) Reset() {
	*x = YieldPrediction{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YieldPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YieldPrediction) ProtoMessage() {}

func (x *YieldPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YieldPrediction.ProtoReflect.Descriptor instead.
func (*YieldPrediction) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{1}
}

func (x *YieldPrediction) GetYieldKw() int64 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

func (x *YieldPrediction) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *YieldPrediction) GetUncertainty() *YieldPrediction_Uncertainty {
	if x != nil {
		return x.Uncertainty
	}
	return nil
}

type YieldDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaKw       int64                  `protobuf:"zigzag64,1,opt,name=delta_kw,json=deltaKw,proto3" json:"delta_kw,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YieldDelta) Reset() {
	*x = YieldDelta{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YieldDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YieldDelta) ProtoMessage() {}

func (x *YieldDelta) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YieldDelta.ProtoReflect.Descriptor instead.
func (*YieldDelta) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{2}
}

func (x *YieldDelta) GetDeltaKw() int64 {
	if x != nil {
		return x.DeltaKw
	}
	return 0
}

func (x *YieldDelta) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type GetPredictedTimeseriesRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	LocationIds  []int32                `protobuf:"varint,1,rep,packed,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	EnergySource EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	// * The desired minimum difference between the forecast initialisation time,
	// and each target time in minutes.
	// A value of 0 gives the most recently predicted values for each target time (default).
	HorizonMins   int32 `protobuf:"varint,3,opt,name=horizon_mins,json=horizonMins,proto3" json:"horizon_mins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedTimeseriesRequest) Reset() {
	*x = GetPredictedTimeseriesRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedTimeseriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedTimeseriesRequest) ProtoMessage() {}

func (x *GetPredictedTimeseriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedTimeseriesRequest.ProtoReflect.Descriptor instead.
func (*GetPredictedTimeseriesRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetPredictedTimeseriesRequest) GetLocationIds() []int32 {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *GetPredictedTimeseriesRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *GetPredictedTimeseriesRequest) GetHorizonMins() int32 {
	if x != nil {
		return x.HorizonMins
	}
	return 0
}

type GetPredictedTimeseriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Yields        []*YieldPrediction     `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedTimeseriesResponse) Reset() {
	*x = GetPredictedTimeseriesResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedTimeseriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedTimeseriesResponse) ProtoMessage() {}

func (x *GetPredictedTimeseriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedTimeseriesResponse.ProtoReflect.Descriptor instead.
func (*GetPredictedTimeseriesResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetPredictedTimeseriesResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetPredictedTimeseriesResponse) GetYields() []*YieldPrediction {
	if x != nil {
		return x.Yields
	}
	return nil
}

type GetPredictedTimeseriesDeltasRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	LocationId   int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	EnergySource EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	// * The desired difference between the initialisation time and the target time in minutes.
	// 0 gives the most recently predicted deltas, and is the default if not specified.
	HorizonMins int32 `protobuf:"varint,3,opt,name=horizon_mins,json=horizonMins,proto3" json:"horizon_mins,omitempty"`
	// * The name of the desired model to fetch predicted yields from.
	// If not specified, the default model will be used.
	ModelName string `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// * The version of the model to fetch predicted yields from.
	// If not specified, the latest version of the named model will be used.
	ModelVersion string `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// * The name of the provider of observed yields to fetch from.
	// If not specified, the default observer will be used.
	ObserverName  string `protobuf:"bytes,6,opt,name=observer_name,json=observerName,proto3" json:"observer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedTimeseriesDeltasRequest) Reset() {
	*x = GetPredictedTimeseriesDeltasRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedTimeseriesDeltasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedTimeseriesDeltasRequest) ProtoMessage() {}

func (x *GetPredictedTimeseriesDeltasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedTimeseriesDeltasRequest.ProtoReflect.Descriptor instead.
func (*GetPredictedTimeseriesDeltasRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetPredictedTimeseriesDeltasRequest) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetPredictedTimeseriesDeltasRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *GetPredictedTimeseriesDeltasRequest) GetHorizonMins() int32 {
	if x != nil {
		return x.HorizonMins
	}
	return 0
}

func (x *GetPredictedTimeseriesDeltasRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetPredictedTimeseriesDeltasRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *GetPredictedTimeseriesDeltasRequest) GetObserverName() string {
	if x != nil {
		return x.ObserverName
	}
	return ""
}

type GetPredictedTimeseriesDeltasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Deltas        []*YieldDelta          `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedTimeseriesDeltasResponse) Reset() {
	*x = GetPredictedTimeseriesDeltasResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedTimeseriesDeltasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedTimeseriesDeltasResponse) ProtoMessage() {}

func (x *GetPredictedTimeseriesDeltasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedTimeseriesDeltasResponse.ProtoReflect.Descriptor instead.
func (*GetPredictedTimeseriesDeltasResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetPredictedTimeseriesDeltasResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetPredictedTimeseriesDeltasResponse) GetDeltas() []*YieldDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type GetObservedTimeseriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	ObserverName  string                 `protobuf:"bytes,2,opt,name=observer_name,json=observerName,proto3" json:"observer_name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservedTimeseriesRequest) Reset() {
	*x = GetObservedTimeseriesRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservedTimeseriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservedTimeseriesRequest) ProtoMessage() {}

func (x *GetObservedTimeseriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservedTimeseriesRequest.ProtoReflect.Descriptor instead.
func (*GetObservedTimeseriesRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetObservedTimeseriesRequest) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetObservedTimeseriesRequest) GetObserverName() string {
	if x != nil {
		return x.ObserverName
	}
	return ""
}

func (x *GetObservedTimeseriesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetObservedTimeseriesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetObservedTimeseriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Yields        []*Yield               `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservedTimeseriesResponse) Reset() {
	*x = GetObservedTimeseriesResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservedTimeseriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservedTimeseriesResponse) ProtoMessage() {}

func (x *GetObservedTimeseriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservedTimeseriesResponse.ProtoReflect.Descriptor instead.
func (*GetObservedTimeseriesResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetObservedTimeseriesResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetObservedTimeseriesResponse) GetYields() []*Yield {
	if x != nil {
		return x.Yields
	}
	return nil
}

type GetPredictedCrossSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationIds   []int32                `protobuf:"varint,1,rep,packed,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedCrossSectionRequest) Reset() {
	*x = GetPredictedCrossSectionRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedCrossSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedCrossSectionRequest) ProtoMessage() {}

func (x *GetPredictedCrossSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedCrossSectionRequest.ProtoReflect.Descriptor instead.
func (*GetPredictedCrossSectionRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GetPredictedCrossSectionRequest) GetLocationIds() []int32 {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *GetPredictedCrossSectionRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *GetPredictedCrossSectionRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type GetPredictedCrossSectionResponse struct {
	state         protoimpl.MessageState                                        `protogen:"open.v1"`
	TimestampUnix int64                                                         `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Yields        []*GetPredictedCrossSectionResponse_YieldPredictionAtLocation `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedCrossSectionResponse) Reset() {
	*x = GetPredictedCrossSectionResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedCrossSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedCrossSectionResponse) ProtoMessage() {}

func (x *GetPredictedCrossSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedCrossSectionResponse.ProtoReflect.Descriptor instead.
func (*GetPredictedCrossSectionResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{10}
}

func (x *GetPredictedCrossSectionResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *GetPredictedCrossSectionResponse) GetYields() []*GetPredictedCrossSectionResponse_YieldPredictionAtLocation {
	if x != nil {
		return x.Yields
	}
	return nil
}

type GetLatestForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestForecastRequest) Reset() {
	*x = GetLatestForecastRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestForecastRequest) ProtoMessage() {}

func (x *GetLatestForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestForecastRequest.ProtoReflect.Descriptor instead.
func (*GetLatestForecastRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{11}
}

func (x *GetLatestForecastRequest) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetLatestForecastRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

type GetLatestForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	ForecastId    int64                  `protobuf:"varint,2,opt,name=forecast_id,json=forecastId,proto3" json:"forecast_id,omitempty"`
	Yields        []*YieldPrediction     `protobuf:"bytes,3,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestForecastResponse) Reset() {
	*x = GetLatestForecastResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestForecastResponse) ProtoMessage() {}

func (x *GetLatestForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestForecastResponse.ProtoReflect.Descriptor instead.
func (*GetLatestForecastResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{12}
}

func (x *GetLatestForecastResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetLatestForecastResponse) GetForecastId() int64 {
	if x != nil {
		return x.ForecastId
	}
	return 0
}

func (x *GetLatestForecastResponse) GetYields() []*YieldPrediction {
	if x != nil {
		return x.Yields
	}
	return nil
}

type CreateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	MakeDefault   bool                   `protobuf:"varint,3,opt,name=make_default,json=makeDefault,proto3" json:"make_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{13}
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateModelRequest) GetMakeDefault() bool {
	if x != nil {
		return x.MakeDefault
	}
	return false
}

type CreateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       int32                  `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{14}
}

func (x *CreateModelResponse) GetModelId() int32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type CreateForecastRequest struct {
	state                     protoimpl.MessageState                            `protogen:"open.v1"`
	Forecast                  *CreateForecastRequest_Forecast                   `protobuf:"bytes,1,opt,name=forecast,proto3" json:"forecast,omitempty"`
	PredictedGenerationValues []*CreateForecastRequest_PredictedGenerationValue `protobuf:"bytes,2,rep,name=predicted_generation_values,json=predictedGenerationValues,proto3" json:"predicted_generation_values,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateForecastRequest) Reset() {
	*x = CreateForecastRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastRequest) ProtoMessage() {}

func (x *CreateForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastRequest.ProtoReflect.Descriptor instead.
func (*CreateForecastRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{15}
}

func (x *CreateForecastRequest) GetForecast() *CreateForecastRequest_Forecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *CreateForecastRequest) GetPredictedGenerationValues() []*CreateForecastRequest_PredictedGenerationValue {
	if x != nil {
		return x.PredictedGenerationValues
	}
	return nil
}

type CreateForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForecastId    int64                  `protobuf:"varint,1,opt,name=forecast_id,json=forecastId,proto3" json:"forecast_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForecastResponse) Reset() {
	*x = CreateForecastResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastResponse) ProtoMessage() {}

func (x *CreateForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastResponse.ProtoReflect.Descriptor instead.
func (*CreateForecastResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{16}
}

func (x *CreateForecastResponse) GetForecastId() int64 {
	if x != nil {
		return x.ForecastId
	}
	return 0
}

type CreateSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	Latitude      float32                `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CapacityKw    int64                  `protobuf:"varint,5,opt,name=capacity_kw,json=capacityKw,proto3" json:"capacity_kw,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSiteRequest) Reset() {
	*x = CreateSiteRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteRequest) ProtoMessage() {}

func (x *CreateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteRequest.ProtoReflect.Descriptor instead.
func (*CreateSiteRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{17}
}

func (x *CreateSiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSiteRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *CreateSiteRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateSiteRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateSiteRequest) GetCapacityKw() int64 {
	if x != nil {
		return x.CapacityKw
	}
	return 0
}

func (x *CreateSiteRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CreateSiteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSiteResponse) Reset() {
	*x = CreateSiteResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteResponse) ProtoMessage() {}

func (x *CreateSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteResponse.ProtoReflect.Descriptor instead.
func (*CreateSiteResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{18}
}

func (x *CreateSiteResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

type CreateGspRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	Geometry      string                 `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
	CapacityMw    int64                  `protobuf:"varint,4,opt,name=capacity_mw,json=capacityMw,proto3" json:"capacity_mw,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGspRequest) Reset() {
	*x = CreateGspRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGspRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGspRequest) ProtoMessage() {}

func (x *CreateGspRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGspRequest.ProtoReflect.Descriptor instead.
func (*CreateGspRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{19}
}

func (x *CreateGspRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGspRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *CreateGspRequest) GetGeometry() string {
	if x != nil {
		return x.Geometry
	}
	return ""
}

func (x *CreateGspRequest) GetCapacityMw() int64 {
	if x != nil {
		return x.CapacityMw
	}
	return 0
}

func (x *CreateGspRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CreateGspResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGspResponse) Reset() {
	*x = CreateGspResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGspResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGspResponse) ProtoMessage() {}

func (x *CreateGspResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGspResponse.ProtoReflect.Descriptor instead.
func (*CreateGspResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{20}
}

func (x *CreateGspResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{21}
}

func (x *GetLocationRequest) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetLocationRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

type GetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float32                `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CapacityKw    int64                  `protobuf:"varint,5,opt,name=capacity_kw,json=capacityKw,proto3" json:"capacity_kw,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{22}
}

func (x *GetLocationResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetLocationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLocationResponse) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetLocationResponse) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetLocationResponse) GetCapacityKw() int64 {
	if x != nil {
		return x.CapacityKw
	}
	return 0
}

func (x *GetLocationResponse) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type GetLocationsAsGeoJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationIds   []int32                `protobuf:"varint,1,rep,packed,name=location_ids,json=locationIds,proto3" json:"location_ids,omitempty"`
	Unsimplified  bool                   `protobuf:"varint,2,opt,name=unsimplified,proto3" json:"unsimplified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationsAsGeoJSONRequest) Reset() {
	*x = GetLocationsAsGeoJSONRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationsAsGeoJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationsAsGeoJSONRequest) ProtoMessage() {}

func (x *GetLocationsAsGeoJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationsAsGeoJSONRequest.ProtoReflect.Descriptor instead.
func (*GetLocationsAsGeoJSONRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{23}
}

func (x *GetLocationsAsGeoJSONRequest) GetLocationIds() []int32 {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *GetLocationsAsGeoJSONRequest) GetUnsimplified() bool {
	if x != nil {
		return x.Unsimplified
	}
	return false
}

type GetLocationsAsGeoJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geojson       string                 `protobuf:"bytes,1,opt,name=geojson,proto3" json:"geojson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationsAsGeoJSONResponse) Reset() {
	*x = GetLocationsAsGeoJSONResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationsAsGeoJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationsAsGeoJSONResponse) ProtoMessage() {}

func (x *GetLocationsAsGeoJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationsAsGeoJSONResponse.ProtoReflect.Descriptor instead.
func (*GetLocationsAsGeoJSONResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{24}
}

func (x *GetLocationsAsGeoJSONResponse) GetGeojson() string {
	if x != nil {
		return x.Geojson
	}
	return ""
}

type CreateObservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,2,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	ObserverName  string                 `protobuf:"bytes,3,opt,name=observer_name,json=observerName,proto3" json:"observer_name,omitempty"`
	Yields        []*Yield               `protobuf:"bytes,4,rep,name=yields,proto3" json:"yields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObservationsRequest) Reset() {
	*x = CreateObservationsRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObservationsRequest) ProtoMessage() {}

func (x *CreateObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObservationsRequest.ProtoReflect.Descriptor instead.
func (*CreateObservationsRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{25}
}

func (x *CreateObservationsRequest) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *CreateObservationsRequest) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *CreateObservationsRequest) GetObserverName() string {
	if x != nil {
		return x.ObserverName
	}
	return ""
}

func (x *CreateObservationsRequest) GetYields() []*Yield {
	if x != nil {
		return x.Yields
	}
	return nil
}

type CreateObservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObservationsResponse) Reset() {
	*x = CreateObservationsResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObservationsResponse) ProtoMessage() {}

func (x *CreateObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObservationsResponse.ProtoReflect.Descriptor instead.
func (*CreateObservationsResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{26}
}

type CreateObserverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObserverRequest) Reset() {
	*x = CreateObserverRequest{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObserverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObserverRequest) ProtoMessage() {}

func (x *CreateObserverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObserverRequest.ProtoReflect.Descriptor instead.
func (*CreateObserverRequest) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{27}
}

func (x *CreateObserverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateObserverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObserverId    int32                  `protobuf:"varint,1,opt,name=observer_id,json=observerId,proto3" json:"observer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObserverResponse) Reset() {
	*x = CreateObserverResponse{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObserverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObserverResponse) ProtoMessage() {}

func (x *CreateObserverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObserverResponse.ProtoReflect.Descriptor instead.
func (*CreateObserverResponse) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{28}
}

func (x *CreateObserverResponse) GetObserverId() int32 {
	if x != nil {
		return x.ObserverId
	}
	return 0
}

type YieldPrediction_Uncertainty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LowerKw       int64                  `protobuf:"varint,1,opt,name=lower_kw,json=lowerKw,proto3" json:"lower_kw,omitempty"`
	UpperKw       int64                  `protobuf:"varint,2,opt,name=upper_kw,json=upperKw,proto3" json:"upper_kw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YieldPrediction_Uncertainty) Reset() {
	*x = YieldPrediction_Uncertainty{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YieldPrediction_Uncertainty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YieldPrediction_Uncertainty) ProtoMessage() {}

func (x *YieldPrediction_Uncertainty) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YieldPrediction_Uncertainty.ProtoReflect.Descriptor instead.
func (*YieldPrediction_Uncertainty) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{1, 0}
}

func (x *YieldPrediction_Uncertainty) GetLowerKw() int64 {
	if x != nil {
		return x.LowerKw
	}
	return 0
}

func (x *YieldPrediction_Uncertainty) GetUpperKw() int64 {
	if x != nil {
		return x.UpperKw
	}
	return 0
}

type GetPredictedCrossSectionResponse_YieldPredictionAtLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int32                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	YieldKw       int64                  `protobuf:"varint,2,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredictedCrossSectionResponse_YieldPredictionAtLocation) Reset() {
	*x = GetPredictedCrossSectionResponse_YieldPredictionAtLocation{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredictedCrossSectionResponse_YieldPredictionAtLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedCrossSectionResponse_YieldPredictionAtLocation) ProtoMessage() {}

func (x *GetPredictedCrossSectionResponse_YieldPredictionAtLocation) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedCrossSectionResponse_YieldPredictionAtLocation.ProtoReflect.Descriptor instead.
func (*GetPredictedCrossSectionResponse_YieldPredictionAtLocation) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GetPredictedCrossSectionResponse_YieldPredictionAtLocation) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *GetPredictedCrossSectionResponse_YieldPredictionAtLocation) GetYieldKw() int64 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

type CreateForecastRequest_PredictedGenerationValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HorizonMins   int32                  `protobuf:"varint,1,opt,name=horizon_mins,json=horizonMins,proto3" json:"horizon_mins,omitempty"`
	P50Pct        float32                `protobuf:"fixed32,2,opt,name=p50_pct,json=p50Pct,proto3" json:"p50_pct,omitempty"`
	P10Pct        float32                `protobuf:"fixed32,3,opt,name=p10_pct,json=p10Pct,proto3" json:"p10_pct,omitempty"`
	P90Pct        float32                `protobuf:"fixed32,4,opt,name=p90_pct,json=p90Pct,proto3" json:"p90_pct,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForecastRequest_PredictedGenerationValue) Reset() {
	*x = CreateForecastRequest_PredictedGenerationValue{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastRequest_PredictedGenerationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastRequest_PredictedGenerationValue) ProtoMessage() {}

func (x *CreateForecastRequest_PredictedGenerationValue) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastRequest_PredictedGenerationValue.ProtoReflect.Descriptor instead.
func (*CreateForecastRequest_PredictedGenerationValue) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{15, 0}
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetHorizonMins() int32 {
	if x != nil {
		return x.HorizonMins
	}
	return 0
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetP50Pct() float32 {
	if x != nil {
		return x.P50Pct
	}
	return 0
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetP10Pct() float32 {
	if x != nil {
		return x.P10Pct
	}
	return 0
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetP90Pct() float32 {
	if x != nil {
		return x.P90Pct
	}
	return 0
}

func (x *CreateForecastRequest_PredictedGenerationValue) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CreateForecastRequest_Forecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       int32                  `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	LocationId    int32                  `protobuf:"varint,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	EnergySource  EnergySource           `protobuf:"varint,3,opt,name=energy_source,json=energySource,proto3,enum=ocf.dp.EnergySource" json:"energy_source,omitempty"`
	InitTimeUtc   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=init_time_utc,json=initTimeUtc,proto3" json:"init_time_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForecastRequest_Forecast) Reset() {
	*x = CreateForecastRequest_Forecast{}
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastRequest_Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastRequest_Forecast) ProtoMessage() {}

func (x *CreateForecastRequest_Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_ocf_dp_dp_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastRequest_Forecast.ProtoReflect.Descriptor instead.
func (*CreateForecastRequest_Forecast) Descriptor() ([]byte, []int) {
	return file_ocf_dp_dp_messages_proto_rawDescGZIP(), []int{15, 1}
}

func (x *CreateForecastRequest_Forecast) GetModelId() int32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *CreateForecastRequest_Forecast) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *CreateForecastRequest_Forecast) GetEnergySource() EnergySource {
	if x != nil {
		return x.EnergySource
	}
	return EnergySource_ENERGY_SOURCE_UNSPECIFIED
}

func (x *CreateForecastRequest_Forecast) GetInitTimeUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.InitTimeUtc
	}
	return nil
}

var File_ocf_dp_dp_messages_proto protoreflect.FileDescriptor

const file_ocf_dp_dp_messages_proto_rawDesc = "" +
	"\n" +
	"\x18ocf/dp/dp.messages.proto\x12\x06ocf.dp\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\x05Yield\x12\x19\n" +
	"\byield_kw\x18\x01 \x01(\x03R\ayieldKw\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\"\xdf\x01\n" +
	"\x0fYieldPrediction\x12\x19\n" +
	"\byield_kw\x18\x01 \x01(\x03R\ayieldKw\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\x12E\n" +
	"\vuncertainty\x18\x03 \x01(\v2#.ocf.dp.YieldPrediction.UncertaintyR\vuncertainty\x1aC\n" +
	"\vUncertainty\x12\x19\n" +
	"\blower_kw\x18\x01 \x01(\x03R\alowerKw\x12\x19\n" +
	"\bupper_kw\x18\x02 \x01(\x03R\aupperKw\"N\n" +
	"\n" +
	"YieldDelta\x12\x19\n" +
	"\bdelta_kw\x18\x01 \x01(\x12R\adeltaKw\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\"\xa0\x01\n" +
	"\x1dGetPredictedTimeseriesRequest\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\x05R\vlocationIds\x129\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\x12!\n" +
	"\fhorizon_mins\x18\x03 \x01(\x05R\vhorizonMins\"r\n" +
	"\x1eGetPredictedTimeseriesResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12/\n" +
	"\x06yields\x18\x02 \x03(\v2\x17.ocf.dp.YieldPredictionR\x06yields\"\x8d\x02\n" +
	"#GetPredictedTimeseriesDeltasRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x129\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\x12!\n" +
	"\fhorizon_mins\x18\x03 \x01(\x05R\vhorizonMins\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x05 \x01(\tR\fmodelVersion\x12#\n" +
	"\robserver_name\x18\x06 \x01(\tR\fobserverName\"s\n" +
	"$GetPredictedTimeseriesDeltasResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12*\n" +
	"\x06deltas\x18\x02 \x03(\v2\x12.ocf.dp.YieldDeltaR\x06deltas\"\xd6\x01\n" +
	"\x1cGetObservedTimeseriesRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12#\n" +
	"\robserver_name\x18\x02 \x01(\tR\fobserverName\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"g\n" +
	"\x1dGetObservedTimeseriesResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12%\n" +
	"\x06yields\x18\x02 \x03(\v2\r.ocf.dp.YieldR\x06yields\"\xa6\x01\n" +
	"\x1fGetPredictedCrossSectionRequest\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\x05R\vlocationIds\x129\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\"\xfe\x01\n" +
	" GetPredictedCrossSectionResponse\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x12Z\n" +
	"\x06yields\x18\x02 \x03(\v2B.ocf.dp.GetPredictedCrossSectionResponse.YieldPredictionAtLocationR\x06yields\x1aW\n" +
	"\x19YieldPredictionAtLocation\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12\x19\n" +
	"\byield_kw\x18\x02 \x01(\x03R\ayieldKw\"v\n" +
	"\x18GetLatestForecastRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x129\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\"\x8e\x01\n" +
	"\x19GetLatestForecastResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12\x1f\n" +
	"\vforecast_id\x18\x02 \x01(\x03R\n" +
	"forecastId\x12/\n" +
	"\x06yields\x18\x03 \x03(\v2\x17.ocf.dp.YieldPredictionR\x06yields\"e\n" +
	"\x12CreateModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fmake_default\x18\x03 \x01(\bR\vmakeDefault\"0\n" +
	"\x13CreateModelResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x05R\amodelId\"\xbe\x04\n" +
	"\x15CreateForecastRequest\x12B\n" +
	"\bforecast\x18\x01 \x01(\v2&.ocf.dp.CreateForecastRequest.ForecastR\bforecast\x12v\n" +
	"\x1bpredicted_generation_values\x18\x02 \x03(\v26.ocf.dp.CreateForecastRequest.PredictedGenerationValueR\x19predictedGenerationValues\x1a\xa4\x01\n" +
	"\x18PredictedGenerationValue\x12!\n" +
	"\fhorizon_mins\x18\x01 \x01(\x05R\vhorizonMins\x12\x17\n" +
	"\ap50_pct\x18\x02 \x01(\x02R\x06p50Pct\x12\x17\n" +
	"\ap10_pct\x18\x03 \x01(\x02R\x06p10Pct\x12\x17\n" +
	"\ap90_pct\x18\x04 \x01(\x02R\x06p90Pct\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\x1a\xc1\x01\n" +
	"\bForecast\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x05R\amodelId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\x05R\n" +
	"locationId\x129\n" +
	"\renergy_source\x18\x03 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\x12>\n" +
	"\rinit_time_utc\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vinitTimeUtc\"9\n" +
	"\x16CreateForecastResponse\x12\x1f\n" +
	"\vforecast_id\x18\x01 \x01(\x03R\n" +
	"forecastId\"\xd9\x01\n" +
	"\x11CreateSiteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x02R\tlongitude\x12\x1f\n" +
	"\vcapacity_kw\x18\x05 \x01(\x03R\n" +
	"capacityKw\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"5\n" +
	"\x12CreateSiteResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\"\xba\x01\n" +
	"\x10CreateGspRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\x12\x1a\n" +
	"\bgeometry\x18\x03 \x01(\tR\bgeometry\x12\x1f\n" +
	"\vcapacity_mw\x18\x04 \x01(\x03R\n" +
	"capacityMw\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"4\n" +
	"\x11CreateGspResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\"p\n" +
	"\x12GetLocationRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x129\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\"\xc1\x01\n" +
	"\x13GetLocationResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x02R\tlongitude\x12\x1f\n" +
	"\vcapacity_kw\x18\x05 \x01(\x03R\n" +
	"capacityKw\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"e\n" +
	"\x1cGetLocationsAsGeoJSONRequest\x12!\n" +
	"\flocation_ids\x18\x01 \x03(\x05R\vlocationIds\x12\"\n" +
	"\funsimplified\x18\x02 \x01(\bR\funsimplified\"9\n" +
	"\x1dGetLocationsAsGeoJSONResponse\x12\x18\n" +
	"\ageojson\x18\x01 \x01(\tR\ageojson\"\xc3\x01\n" +
	"\x19CreateObservationsRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x05R\n" +
	"locationId\x129\n" +
	"\renergy_source\x18\x02 \x01(\x0e2\x14.ocf.dp.EnergySourceR\fenergySource\x12#\n" +
	"\robserver_name\x18\x03 \x01(\tR\fobserverName\x12%\n" +
	"\x06yields\x18\x04 \x03(\v2\r.ocf.dp.YieldR\x06yields\"\x1c\n" +
	"\x1aCreateObservationsResponse\"+\n" +
	"\x15CreateObserverRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\x16CreateObserverResponse\x12\x1f\n" +
	"\vobserver_id\x18\x01 \x01(\x05R\n" +
	"observerId*^\n" +
	"\fEnergySource\x12\x1d\n" +
	"\x19ENERGY_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ENERGY_SOURCE_SOLAR\x10\x01\x12\x16\n" +
	"\x12ENERGY_SOURCE_WIND\x10\x02B7Z5github.com/devsjc/fcfs/dp/internal/protogen/ocf/dp;dpb\x06proto3"

var (
	file_ocf_dp_dp_messages_proto_rawDescOnce sync.Once
	file_ocf_dp_dp_messages_proto_rawDescData []byte
)

func file_ocf_dp_dp_messages_proto_rawDescGZIP() []byte {
	file_ocf_dp_dp_messages_proto_rawDescOnce.Do(func() {
		file_ocf_dp_dp_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocf_dp_dp_messages_proto_rawDesc), len(file_ocf_dp_dp_messages_proto_rawDesc)))
	})
	return file_ocf_dp_dp_messages_proto_rawDescData
}

var file_ocf_dp_dp_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ocf_dp_dp_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_ocf_dp_dp_messages_proto_goTypes = []any{
	(EnergySource)(0),                                                  // 0: ocf.dp.EnergySource
	(*Yield)(nil),                                                      // 1: ocf.dp.Yield
	(*YieldPrediction)(nil),                                            // 2: ocf.dp.YieldPrediction
	(*YieldDelta)(nil),                                                 // 3: ocf.dp.YieldDelta
	(*GetPredictedTimeseriesRequest)(nil),                              // 4: ocf.dp.GetPredictedTimeseriesRequest
	(*GetPredictedTimeseriesResponse)(nil),                             // 5: ocf.dp.GetPredictedTimeseriesResponse
	(*GetPredictedTimeseriesDeltasRequest)(nil),                        // 6: ocf.dp.GetPredictedTimeseriesDeltasRequest
	(*GetPredictedTimeseriesDeltasResponse)(nil),                       // 7: ocf.dp.GetPredictedTimeseriesDeltasResponse
	(*GetObservedTimeseriesRequest)(nil),                               // 8: ocf.dp.GetObservedTimeseriesRequest
	(*GetObservedTimeseriesResponse)(nil),                              // 9: ocf.dp.GetObservedTimeseriesResponse
	(*GetPredictedCrossSectionRequest)(nil),                            // 10: ocf.dp.GetPredictedCrossSectionRequest
	(*GetPredictedCrossSectionResponse)(nil),                           // 11: ocf.dp.GetPredictedCrossSectionResponse
	(*GetLatestForecastRequest)(nil),                                   // 12: ocf.dp.GetLatestForecastRequest
	(*GetLatestForecastResponse)(nil),                                  // 13: ocf.dp.GetLatestForecastResponse
	(*CreateModelRequest)(nil),                                         // 14: ocf.dp.CreateModelRequest
	(*CreateModelResponse)(nil),                                        // 15: ocf.dp.CreateModelResponse
	(*CreateForecastRequest)(nil),                                      // 16: ocf.dp.CreateForecastRequest
	(*CreateForecastResponse)(nil),                                     // 17: ocf.dp.CreateForecastResponse
	(*CreateSiteRequest)(nil),                                          // 18: ocf.dp.CreateSiteRequest
	(*CreateSiteResponse)(nil),                                         // 19: ocf.dp.CreateSiteResponse
	(*CreateGspRequest)(nil),                                           // 20: ocf.dp.CreateGspRequest
	(*CreateGspResponse)(nil),                                          // 21: ocf.dp.CreateGspResponse
	(*GetLocationRequest)(nil),                                         // 22: ocf.dp.GetLocationRequest
	(*GetLocationResponse)(nil),                                        // 23: ocf.dp.GetLocationResponse
	(*GetLocationsAsGeoJSONRequest)(nil),                               // 24: ocf.dp.GetLocationsAsGeoJSONRequest
	(*GetLocationsAsGeoJSONResponse)(nil),                              // 25: ocf.dp.GetLocationsAsGeoJSONResponse
	(*CreateObservationsRequest)(nil),                                  // 26: ocf.dp.CreateObservationsRequest
	(*CreateObservationsResponse)(nil),                                 // 27: ocf.dp.CreateObservationsResponse
	(*CreateObserverRequest)(nil),                                      // 28: ocf.dp.CreateObserverRequest
	(*CreateObserverResponse)(nil),                                     // 29: ocf.dp.CreateObserverResponse
	(*YieldPrediction_Uncertainty)(nil),                                // 30: ocf.dp.YieldPrediction.Uncertainty
	(*GetPredictedCrossSectionResponse_YieldPredictionAtLocation)(nil), // 31: ocf.dp.GetPredictedCrossSectionResponse.YieldPredictionAtLocation
	(*CreateForecastRequest_PredictedGenerationValue)(nil),             // 32: ocf.dp.CreateForecastRequest.PredictedGenerationValue
	(*CreateForecastRequest_Forecast)(nil),                             // 33: ocf.dp.CreateForecastRequest.Forecast
	(*timestamppb.Timestamp)(nil),                                      // 34: google.protobuf.Timestamp
}
var file_ocf_dp_dp_messages_proto_depIdxs = []int32{
	30, // 0: ocf.dp.YieldPrediction.uncertainty:type_name -> ocf.dp.YieldPrediction.Uncertainty
	0,  // 1: ocf.dp.GetPredictedTimeseriesRequest.energy_source:type_name -> ocf.dp.EnergySource
	2,  // 2: ocf.dp.GetPredictedTimeseriesResponse.yields:type_name -> ocf.dp.YieldPrediction
	0,  // 3: ocf.dp.GetPredictedTimeseriesDeltasRequest.energy_source:type_name -> ocf.dp.EnergySource
	3,  // 4: ocf.dp.GetPredictedTimeseriesDeltasResponse.deltas:type_name -> ocf.dp.YieldDelta
	34, // 5: ocf.dp.GetObservedTimeseriesRequest.start_time:type_name -> google.protobuf.Timestamp
	34, // 6: ocf.dp.GetObservedTimeseriesRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 7: ocf.dp.GetObservedTimeseriesResponse.yields:type_name -> ocf.dp.Yield
	0,  // 8: ocf.dp.GetPredictedCrossSectionRequest.energy_source:type_name -> ocf.dp.EnergySource
	31, // 9: ocf.dp.GetPredictedCrossSectionResponse.yields:type_name -> ocf.dp.GetPredictedCrossSectionResponse.YieldPredictionAtLocation
	0,  // 10: ocf.dp.GetLatestForecastRequest.energy_source:type_name -> ocf.dp.EnergySource
	2,  // 11: ocf.dp.GetLatestForecastResponse.yields:type_name -> ocf.dp.YieldPrediction
	33, // 12: ocf.dp.CreateForecastRequest.forecast:type_name -> ocf.dp.CreateForecastRequest.Forecast
	32, // 13: ocf.dp.CreateForecastRequest.predicted_generation_values:type_name -> ocf.dp.CreateForecastRequest.PredictedGenerationValue
	0,  // 14: ocf.dp.CreateSiteRequest.energy_source:type_name -> ocf.dp.EnergySource
	0,  // 15: ocf.dp.CreateGspRequest.energy_source:type_name -> ocf.dp.EnergySource
	0,  // 16: ocf.dp.GetLocationRequest.energy_source:type_name -> ocf.dp.EnergySource
	0,  // 17: ocf.dp.CreateObservationsRequest.energy_source:type_name -> ocf.dp.EnergySource
	1,  // 18: ocf.dp.CreateObservationsRequest.yields:type_name -> ocf.dp.Yield
	0,  // 19: ocf.dp.CreateForecastRequest.Forecast.energy_source:type_name -> ocf.dp.EnergySource
	34, // 20: ocf.dp.CreateForecastRequest.Forecast.init_time_utc:type_name -> google.protobuf.Timestamp
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_ocf_dp_dp_messages_proto_init() }
func file_ocf_dp_dp_messages_proto_init() {
	if File_ocf_dp_dp_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocf_dp_dp_messages_proto_rawDesc), len(file_ocf_dp_dp_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocf_dp_dp_messages_proto_goTypes,
		DependencyIndexes: file_ocf_dp_dp_messages_proto_depIdxs,
		EnumInfos:         file_ocf_dp_dp_messages_proto_enumTypes,
		MessageInfos:      file_ocf_dp_dp_messages_proto_msgTypes,
	}.Build()
	File_ocf_dp_dp_messages_proto = out.File
	file_ocf_dp_dp_messages_proto_goTypes = nil
	file_ocf_dp_dp_messages_proto_depIdxs = nil
}
