// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ocf/dp/dp.service.proto

package dp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ocf_dp_dp_service_proto protoreflect.FileDescriptor

const file_ocf_dp_dp_service_proto_rawDesc = "" +
	"\n" +
	"\x17ocf/dp/dp.service.proto\x12\x06ocf.dp\x1a\x18ocf/dp/dp.messages.proto2\xac\n" +
	"\n" +
	"\x13DataPlatformService\x12i\n" +
	"\x16GetPredictedTimeseries\x12%.ocf.dp.GetPredictedTimeseriesRequest\x1a&.ocf.dp.GetPredictedTimeseriesResponse\"\x00\x12{\n" +
	"\x1cGetPredictedTimeseriesDeltas\x12+.ocf.dp.GetPredictedTimeseriesDeltasRequest\x1a,.ocf.dp.GetPredictedTimeseriesDeltasResponse\"\x00\x12o\n" +
	"\x18GetPredictedCrossSection\x12'.ocf.dp.GetPredictedCrossSectionRequest\x1a(.ocf.dp.GetPredictedCrossSectionResponse\"\x00\x12f\n" +
	"\x15GetObservedTimeseries\x12$.ocf.dp.GetObservedTimeseriesRequest\x1a%.ocf.dp.GetObservedTimeseriesResponse\"\x00\x12c\n" +
	"\x14GetLatestPredictions\x12#.ocf.dp.GetLatestPredictionsRequest\x1a$.ocf.dp.GetLatestPredictionsResponse\"\x00\x12f\n" +
	"\x15GetLocationsAsGeoJSON\x12$.ocf.dp.GetLocationsAsGeoJSONRequest\x1a%.ocf.dp.GetLocationsAsGeoJSONResponse\"\x00\x12E\n" +
	"\n" +
	"CreateSite\x12\x19.ocf.dp.CreateSiteRequest\x1a\x1a.ocf.dp.CreateSiteResponse\"\x00\x12B\n" +
	"\tCreateGsp\x12\x18.ocf.dp.CreateGspRequest\x1a\x19.ocf.dp.CreateGspResponse\"\x00\x12H\n" +
	"\vGetLocation\x12\x1a.ocf.dp.GetLocationRequest\x1a\x1b.ocf.dp.GetLocationResponse\"\x00\x12H\n" +
	"\vCreateModel\x12\x1a.ocf.dp.CreateModelRequest\x1a\x1b.ocf.dp.CreateModelResponse\"\x00\x12Q\n" +
	"\x0eCreateForecast\x12\x1d.ocf.dp.CreateForecastRequest\x1a\x1e.ocf.dp.CreateForecastResponse\"\x00\x12Q\n" +
	"\x0eCreateObserver\x12\x1d.ocf.dp.CreateObserverRequest\x1a\x1e.ocf.dp.CreateObserverResponse\"\x00\x12]\n" +
	"\x12CreateObservations\x12!.ocf.dp.CreateObservationsRequest\x1a\".ocf.dp.CreateObservationsResponse\"\x00\x12c\n" +
	"\x14GetWeekAverageDeltas\x12#.ocf.dp.GetWeekAverageDeltasRequest\x1a$.ocf.dp.GetWeekAverageDeltasResponse\"\x00B7Z5github.com/devsjc/fcfs/dp/internal/protogen/ocf/dp;dpb\x06proto3"

var file_ocf_dp_dp_service_proto_goTypes = []any{
	(*GetPredictedTimeseriesRequest)(nil),        // 0: ocf.dp.GetPredictedTimeseriesRequest
	(*GetPredictedTimeseriesDeltasRequest)(nil),  // 1: ocf.dp.GetPredictedTimeseriesDeltasRequest
	(*GetPredictedCrossSectionRequest)(nil),      // 2: ocf.dp.GetPredictedCrossSectionRequest
	(*GetObservedTimeseriesRequest)(nil),         // 3: ocf.dp.GetObservedTimeseriesRequest
	(*GetLatestPredictionsRequest)(nil),          // 4: ocf.dp.GetLatestPredictionsRequest
	(*GetLocationsAsGeoJSONRequest)(nil),         // 5: ocf.dp.GetLocationsAsGeoJSONRequest
	(*CreateSiteRequest)(nil),                    // 6: ocf.dp.CreateSiteRequest
	(*CreateGspRequest)(nil),                     // 7: ocf.dp.CreateGspRequest
	(*GetLocationRequest)(nil),                   // 8: ocf.dp.GetLocationRequest
	(*CreateModelRequest)(nil),                   // 9: ocf.dp.CreateModelRequest
	(*CreateForecastRequest)(nil),                // 10: ocf.dp.CreateForecastRequest
	(*CreateObserverRequest)(nil),                // 11: ocf.dp.CreateObserverRequest
	(*CreateObservationsRequest)(nil),            // 12: ocf.dp.CreateObservationsRequest
	(*GetWeekAverageDeltasRequest)(nil),          // 13: ocf.dp.GetWeekAverageDeltasRequest
	(*GetPredictedTimeseriesResponse)(nil),       // 14: ocf.dp.GetPredictedTimeseriesResponse
	(*GetPredictedTimeseriesDeltasResponse)(nil), // 15: ocf.dp.GetPredictedTimeseriesDeltasResponse
	(*GetPredictedCrossSectionResponse)(nil),     // 16: ocf.dp.GetPredictedCrossSectionResponse
	(*GetObservedTimeseriesResponse)(nil),        // 17: ocf.dp.GetObservedTimeseriesResponse
	(*GetLatestPredictionsResponse)(nil),         // 18: ocf.dp.GetLatestPredictionsResponse
	(*GetLocationsAsGeoJSONResponse)(nil),        // 19: ocf.dp.GetLocationsAsGeoJSONResponse
	(*CreateSiteResponse)(nil),                   // 20: ocf.dp.CreateSiteResponse
	(*CreateGspResponse)(nil),                    // 21: ocf.dp.CreateGspResponse
	(*GetLocationResponse)(nil),                  // 22: ocf.dp.GetLocationResponse
	(*CreateModelResponse)(nil),                  // 23: ocf.dp.CreateModelResponse
	(*CreateForecastResponse)(nil),               // 24: ocf.dp.CreateForecastResponse
	(*CreateObserverResponse)(nil),               // 25: ocf.dp.CreateObserverResponse
	(*CreateObservationsResponse)(nil),           // 26: ocf.dp.CreateObservationsResponse
	(*GetWeekAverageDeltasResponse)(nil),         // 27: ocf.dp.GetWeekAverageDeltasResponse
}
var file_ocf_dp_dp_service_proto_depIdxs = []int32{
	0,  // 0: ocf.dp.DataPlatformService.GetPredictedTimeseries:input_type -> ocf.dp.GetPredictedTimeseriesRequest
	1,  // 1: ocf.dp.DataPlatformService.GetPredictedTimeseriesDeltas:input_type -> ocf.dp.GetPredictedTimeseriesDeltasRequest
	2,  // 2: ocf.dp.DataPlatformService.GetPredictedCrossSection:input_type -> ocf.dp.GetPredictedCrossSectionRequest
	3,  // 3: ocf.dp.DataPlatformService.GetObservedTimeseries:input_type -> ocf.dp.GetObservedTimeseriesRequest
	4,  // 4: ocf.dp.DataPlatformService.GetLatestPredictions:input_type -> ocf.dp.GetLatestPredictionsRequest
	5,  // 5: ocf.dp.DataPlatformService.GetLocationsAsGeoJSON:input_type -> ocf.dp.GetLocationsAsGeoJSONRequest
	6,  // 6: ocf.dp.DataPlatformService.CreateSite:input_type -> ocf.dp.CreateSiteRequest
	7,  // 7: ocf.dp.DataPlatformService.CreateGsp:input_type -> ocf.dp.CreateGspRequest
	8,  // 8: ocf.dp.DataPlatformService.GetLocation:input_type -> ocf.dp.GetLocationRequest
	9,  // 9: ocf.dp.DataPlatformService.CreateModel:input_type -> ocf.dp.CreateModelRequest
	10, // 10: ocf.dp.DataPlatformService.CreateForecast:input_type -> ocf.dp.CreateForecastRequest
	11, // 11: ocf.dp.DataPlatformService.CreateObserver:input_type -> ocf.dp.CreateObserverRequest
	12, // 12: ocf.dp.DataPlatformService.CreateObservations:input_type -> ocf.dp.CreateObservationsRequest
	13, // 13: ocf.dp.DataPlatformService.GetWeekAverageDeltas:input_type -> ocf.dp.GetWeekAverageDeltasRequest
	14, // 14: ocf.dp.DataPlatformService.GetPredictedTimeseries:output_type -> ocf.dp.GetPredictedTimeseriesResponse
	15, // 15: ocf.dp.DataPlatformService.GetPredictedTimeseriesDeltas:output_type -> ocf.dp.GetPredictedTimeseriesDeltasResponse
	16, // 16: ocf.dp.DataPlatformService.GetPredictedCrossSection:output_type -> ocf.dp.GetPredictedCrossSectionResponse
	17, // 17: ocf.dp.DataPlatformService.GetObservedTimeseries:output_type -> ocf.dp.GetObservedTimeseriesResponse
	18, // 18: ocf.dp.DataPlatformService.GetLatestPredictions:output_type -> ocf.dp.GetLatestPredictionsResponse
	19, // 19: ocf.dp.DataPlatformService.GetLocationsAsGeoJSON:output_type -> ocf.dp.GetLocationsAsGeoJSONResponse
	20, // 20: ocf.dp.DataPlatformService.CreateSite:output_type -> ocf.dp.CreateSiteResponse
	21, // 21: ocf.dp.DataPlatformService.CreateGsp:output_type -> ocf.dp.CreateGspResponse
	22, // 22: ocf.dp.DataPlatformService.GetLocation:output_type -> ocf.dp.GetLocationResponse
	23, // 23: ocf.dp.DataPlatformService.CreateModel:output_type -> ocf.dp.CreateModelResponse
	24, // 24: ocf.dp.DataPlatformService.CreateForecast:output_type -> ocf.dp.CreateForecastResponse
	25, // 25: ocf.dp.DataPlatformService.CreateObserver:output_type -> ocf.dp.CreateObserverResponse
	26, // 26: ocf.dp.DataPlatformService.CreateObservations:output_type -> ocf.dp.CreateObservationsResponse
	27, // 27: ocf.dp.DataPlatformService.GetWeekAverageDeltas:output_type -> ocf.dp.GetWeekAverageDeltasResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ocf_dp_dp_service_proto_init() }
func file_ocf_dp_dp_service_proto_init() {
	if File_ocf_dp_dp_service_proto != nil {
		return
	}
	file_ocf_dp_dp_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocf_dp_dp_service_proto_rawDesc), len(file_ocf_dp_dp_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocf_dp_dp_service_proto_goTypes,
		DependencyIndexes: file_ocf_dp_dp_service_proto_depIdxs,
	}.Build()
	File_ocf_dp_dp_service_proto = out.File
	file_ocf_dp_dp_service_proto_goTypes = nil
	file_ocf_dp_dp_service_proto_depIdxs = nil
}
