// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fcfs/service.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_fcfs_service_proto protoreflect.FileDescriptor

const file_fcfs_service_proto_rawDesc = "" +
	"\n" +
	"\x12fcfs/service.proto\x12\x04fcfs\x1a\x1cfcfs/messages/location.proto\x1a\x1cfcfs/messages/forecast.proto\x1a\x1cfcfs/messages/quartzui.proto2\xb5\t\n" +
	"\tQuartzAPI\x12y\n" +
	"\x16GetPredictedTimeseries\x12,.fcfs.messages.GetPredictedTimeseriesRequest\x1a-.fcfs.messages.GetPredictedTimeseriesResponse\"\x000\x01\x12p\n" +
	"\x13GetActualTimeseries\x12).fcfs.messages.GetActualTimeseriesRequest\x1a*.fcfs.messages.GetActualTimeseriesResponse\"\x000\x01\x12t\n" +
	"\x15GetActualCrossSection\x12+.fcfs.messages.GetActualCrossSectionRequest\x1a,.fcfs.messages.GetActualCrossSectionResponse\"\x00\x12}\n" +
	"\x18GetPredictedCrossSection\x12..fcfs.messages.GetPredictedCrossSectionRequest\x1a/.fcfs.messages.GetPredictedCrossSectionResponse\"\x00\x12\\\n" +
	"\x0fCreateSolarSite\x12 .fcfs.messages.CreateSiteRequest\x1a%.fcfs.messages.CreateLocationResponse\"\x00\x12Z\n" +
	"\x0eCreateSolarGsp\x12\x1f.fcfs.messages.CreateGspRequest\x1a%.fcfs.messages.CreateLocationResponse\"\x00\x12W\n" +
	"\fGetSolarSite\x12!.fcfs.messages.GetLocationRequest\x1a\".fcfs.messages.GetLocationResponse\"\x00\x12V\n" +
	"\vGetSolarGsp\x12!.fcfs.messages.GetLocationRequest\x1a\".fcfs.messages.GetLocationResponse\"\x00\x12V\n" +
	"\vCreateModel\x12!.fcfs.messages.CreateModelRequest\x1a\".fcfs.messages.CreateModelResponse\"\x00\x12g\n" +
	"\x14CreateSolarForecasts\x12%.fcfs.messages.CreateForecastsRequest\x1a&.fcfs.messages.CreateForecastsResponse\"\x00\x12\x99\x01\n" +
	"&CreatePredictedGenerationValuesRequest\x125.fcfs.messages.CreatePredictedGenerationValuesRequest\x1a6.fcfs.messages.CreatePredictedGenerationValuesResponse\"\x00B0Z.github.com/devsjc/fcfs/api/src/internal/modelsb\x06proto3"

var file_fcfs_service_proto_goTypes = []any{
	(*GetPredictedTimeseriesRequest)(nil),           // 0: fcfs.messages.GetPredictedTimeseriesRequest
	(*GetActualTimeseriesRequest)(nil),              // 1: fcfs.messages.GetActualTimeseriesRequest
	(*GetActualCrossSectionRequest)(nil),            // 2: fcfs.messages.GetActualCrossSectionRequest
	(*GetPredictedCrossSectionRequest)(nil),         // 3: fcfs.messages.GetPredictedCrossSectionRequest
	(*CreateSiteRequest)(nil),                       // 4: fcfs.messages.CreateSiteRequest
	(*CreateGspRequest)(nil),                        // 5: fcfs.messages.CreateGspRequest
	(*GetLocationRequest)(nil),                      // 6: fcfs.messages.GetLocationRequest
	(*CreateModelRequest)(nil),                      // 7: fcfs.messages.CreateModelRequest
	(*CreateForecastsRequest)(nil),                  // 8: fcfs.messages.CreateForecastsRequest
	(*CreatePredictedGenerationValuesRequest)(nil),  // 9: fcfs.messages.CreatePredictedGenerationValuesRequest
	(*GetPredictedTimeseriesResponse)(nil),          // 10: fcfs.messages.GetPredictedTimeseriesResponse
	(*GetActualTimeseriesResponse)(nil),             // 11: fcfs.messages.GetActualTimeseriesResponse
	(*GetActualCrossSectionResponse)(nil),           // 12: fcfs.messages.GetActualCrossSectionResponse
	(*GetPredictedCrossSectionResponse)(nil),        // 13: fcfs.messages.GetPredictedCrossSectionResponse
	(*CreateLocationResponse)(nil),                  // 14: fcfs.messages.CreateLocationResponse
	(*GetLocationResponse)(nil),                     // 15: fcfs.messages.GetLocationResponse
	(*CreateModelResponse)(nil),                     // 16: fcfs.messages.CreateModelResponse
	(*CreateForecastsResponse)(nil),                 // 17: fcfs.messages.CreateForecastsResponse
	(*CreatePredictedGenerationValuesResponse)(nil), // 18: fcfs.messages.CreatePredictedGenerationValuesResponse
}
var file_fcfs_service_proto_depIdxs = []int32{
	0,  // 0: fcfs.QuartzAPI.GetPredictedTimeseries:input_type -> fcfs.messages.GetPredictedTimeseriesRequest
	1,  // 1: fcfs.QuartzAPI.GetActualTimeseries:input_type -> fcfs.messages.GetActualTimeseriesRequest
	2,  // 2: fcfs.QuartzAPI.GetActualCrossSection:input_type -> fcfs.messages.GetActualCrossSectionRequest
	3,  // 3: fcfs.QuartzAPI.GetPredictedCrossSection:input_type -> fcfs.messages.GetPredictedCrossSectionRequest
	4,  // 4: fcfs.QuartzAPI.CreateSolarSite:input_type -> fcfs.messages.CreateSiteRequest
	5,  // 5: fcfs.QuartzAPI.CreateSolarGsp:input_type -> fcfs.messages.CreateGspRequest
	6,  // 6: fcfs.QuartzAPI.GetSolarSite:input_type -> fcfs.messages.GetLocationRequest
	6,  // 7: fcfs.QuartzAPI.GetSolarGsp:input_type -> fcfs.messages.GetLocationRequest
	7,  // 8: fcfs.QuartzAPI.CreateModel:input_type -> fcfs.messages.CreateModelRequest
	8,  // 9: fcfs.QuartzAPI.CreateSolarForecasts:input_type -> fcfs.messages.CreateForecastsRequest
	9,  // 10: fcfs.QuartzAPI.CreatePredictedGenerationValuesRequest:input_type -> fcfs.messages.CreatePredictedGenerationValuesRequest
	10, // 11: fcfs.QuartzAPI.GetPredictedTimeseries:output_type -> fcfs.messages.GetPredictedTimeseriesResponse
	11, // 12: fcfs.QuartzAPI.GetActualTimeseries:output_type -> fcfs.messages.GetActualTimeseriesResponse
	12, // 13: fcfs.QuartzAPI.GetActualCrossSection:output_type -> fcfs.messages.GetActualCrossSectionResponse
	13, // 14: fcfs.QuartzAPI.GetPredictedCrossSection:output_type -> fcfs.messages.GetPredictedCrossSectionResponse
	14, // 15: fcfs.QuartzAPI.CreateSolarSite:output_type -> fcfs.messages.CreateLocationResponse
	14, // 16: fcfs.QuartzAPI.CreateSolarGsp:output_type -> fcfs.messages.CreateLocationResponse
	15, // 17: fcfs.QuartzAPI.GetSolarSite:output_type -> fcfs.messages.GetLocationResponse
	15, // 18: fcfs.QuartzAPI.GetSolarGsp:output_type -> fcfs.messages.GetLocationResponse
	16, // 19: fcfs.QuartzAPI.CreateModel:output_type -> fcfs.messages.CreateModelResponse
	17, // 20: fcfs.QuartzAPI.CreateSolarForecasts:output_type -> fcfs.messages.CreateForecastsResponse
	18, // 21: fcfs.QuartzAPI.CreatePredictedGenerationValuesRequest:output_type -> fcfs.messages.CreatePredictedGenerationValuesResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fcfs_service_proto_init() }
func file_fcfs_service_proto_init() {
	if File_fcfs_service_proto != nil {
		return
	}
	file_fcfs_messages_location_proto_init()
	file_fcfs_messages_forecast_proto_init()
	file_fcfs_messages_quartzui_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fcfs_service_proto_rawDesc), len(file_fcfs_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fcfs_service_proto_goTypes,
		DependencyIndexes: file_fcfs_service_proto_depIdxs,
	}.Build()
	File_fcfs_service_proto = out.File
	file_fcfs_service_proto_goTypes = nil
	file_fcfs_service_proto_depIdxs = nil
}
