// Messages for the forecast procedures or the QuartzAPI

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: fcfs/messages/forecast.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_fcfs_messages_forecast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfs_messages_forecast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_fcfs_messages_forecast_proto_rawDescGZIP(), []int{0}
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CreateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       int64                  `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_fcfs_messages_forecast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfs_messages_forecast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_fcfs_messages_forecast_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModelResponse) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type PredictedGenerationValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForecastId    int64                  `protobuf:"varint,1,opt,name=forecast_id,json=forecastId,proto3" json:"forecast_id,omitempty"`
	HorizonMins   int64                  `protobuf:"varint,2,opt,name=horizon_mins,json=horizonMins,proto3" json:"horizon_mins,omitempty"`
	P50           int32                  `protobuf:"varint,3,opt,name=p50,proto3" json:"p50,omitempty"`
	P10           int32                  `protobuf:"varint,4,opt,name=p10,proto3" json:"p10,omitempty"`
	P90           int32                  `protobuf:"varint,5,opt,name=p90,proto3" json:"p90,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictedGenerationValue) Reset() {
	*x = PredictedGenerationValue{}
	mi := &file_fcfs_messages_forecast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictedGenerationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedGenerationValue) ProtoMessage() {}

func (x *PredictedGenerationValue) ProtoReflect() protoreflect.Message {
	mi := &file_fcfs_messages_forecast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedGenerationValue.ProtoReflect.Descriptor instead.
func (*PredictedGenerationValue) Descriptor() ([]byte, []int) {
	return file_fcfs_messages_forecast_proto_rawDescGZIP(), []int{2}
}

func (x *PredictedGenerationValue) GetForecastId() int64 {
	if x != nil {
		return x.ForecastId
	}
	return 0
}

func (x *PredictedGenerationValue) GetHorizonMins() int64 {
	if x != nil {
		return x.HorizonMins
	}
	return 0
}

func (x *PredictedGenerationValue) GetP50() int32 {
	if x != nil {
		return x.P50
	}
	return 0
}

func (x *PredictedGenerationValue) GetP10() int32 {
	if x != nil {
		return x.P10
	}
	return 0
}

func (x *PredictedGenerationValue) GetP90() int32 {
	if x != nil {
		return x.P90
	}
	return 0
}

func (x *PredictedGenerationValue) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type Forecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       int64                  `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	InitTimeUtc   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=init_time_utc,json=initTimeUtc,proto3" json:"init_time_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	mi := &file_fcfs_messages_forecast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_fcfs_messages_forecast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_fcfs_messages_forecast_proto_rawDescGZIP(), []int{3}
}

func (x *Forecast) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *Forecast) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Forecast) GetInitTimeUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.InitTimeUtc
	}
	return nil
}

type CreateForecastRequest struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	Forecast                  *Forecast                   `protobuf:"bytes,1,opt,name=forecast,proto3" json:"forecast,omitempty"`
	PredictedGenerationValues []*PredictedGenerationValue `protobuf:"bytes,2,rep,name=predicted_generation_values,json=predictedGenerationValues,proto3" json:"predicted_generation_values,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateForecastRequest) Reset() {
	*x = CreateForecastRequest{}
	mi := &file_fcfs_messages_forecast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastRequest) ProtoMessage() {}

func (x *CreateForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fcfs_messages_forecast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastRequest.ProtoReflect.Descriptor instead.
func (*CreateForecastRequest) Descriptor() ([]byte, []int) {
	return file_fcfs_messages_forecast_proto_rawDescGZIP(), []int{4}
}

func (x *CreateForecastRequest) GetForecast() *Forecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *CreateForecastRequest) GetPredictedGenerationValues() []*PredictedGenerationValue {
	if x != nil {
		return x.PredictedGenerationValues
	}
	return nil
}

type CreateForecastsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForecastId    int64                  `protobuf:"varint,1,opt,name=forecast_id,json=forecastId,proto3" json:"forecast_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForecastsResponse) Reset() {
	*x = CreateForecastsResponse{}
	mi := &file_fcfs_messages_forecast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForecastsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForecastsResponse) ProtoMessage() {}

func (x *CreateForecastsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fcfs_messages_forecast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForecastsResponse.ProtoReflect.Descriptor instead.
func (*CreateForecastsResponse) Descriptor() ([]byte, []int) {
	return file_fcfs_messages_forecast_proto_rawDescGZIP(), []int{5}
}

func (x *CreateForecastsResponse) GetForecastId() int64 {
	if x != nil {
		return x.ForecastId
	}
	return 0
}

var File_fcfs_messages_forecast_proto protoreflect.FileDescriptor

const file_fcfs_messages_forecast_proto_rawDesc = "" +
	"\n" +
	"\x1cfcfs/messages/forecast.proto\x12\rfcfs.messages\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\x12CreateModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"0\n" +
	"\x13CreateModelResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x03R\amodelId\"\xb0\x01\n" +
	"\x18PredictedGenerationValue\x12\x1f\n" +
	"\vforecast_id\x18\x01 \x01(\x03R\n" +
	"forecastId\x12!\n" +
	"\fhorizon_mins\x18\x02 \x01(\x03R\vhorizonMins\x12\x10\n" +
	"\x03p50\x18\x03 \x01(\x05R\x03p50\x12\x10\n" +
	"\x03p10\x18\x04 \x01(\x05R\x03p10\x12\x10\n" +
	"\x03p90\x18\x05 \x01(\x05R\x03p90\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"\x86\x01\n" +
	"\bForecast\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x03R\amodelId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12>\n" +
	"\rinit_time_utc\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vinitTimeUtc\"\xb5\x01\n" +
	"\x15CreateForecastRequest\x123\n" +
	"\bforecast\x18\x01 \x01(\v2\x17.fcfs.messages.ForecastR\bforecast\x12g\n" +
	"\x1bpredicted_generation_values\x18\x02 \x03(\v2'.fcfs.messages.PredictedGenerationValueR\x19predictedGenerationValues\":\n" +
	"\x17CreateForecastsResponse\x12\x1f\n" +
	"\vforecast_id\x18\x01 \x01(\x03R\n" +
	"forecastIdB>Z<github.com/devsjc/fcfs/api/src/internal/models/fcfs/messagesb\x06proto3"

var (
	file_fcfs_messages_forecast_proto_rawDescOnce sync.Once
	file_fcfs_messages_forecast_proto_rawDescData []byte
)

func file_fcfs_messages_forecast_proto_rawDescGZIP() []byte {
	file_fcfs_messages_forecast_proto_rawDescOnce.Do(func() {
		file_fcfs_messages_forecast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fcfs_messages_forecast_proto_rawDesc), len(file_fcfs_messages_forecast_proto_rawDesc)))
	})
	return file_fcfs_messages_forecast_proto_rawDescData
}

var file_fcfs_messages_forecast_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fcfs_messages_forecast_proto_goTypes = []any{
	(*CreateModelRequest)(nil),       // 0: fcfs.messages.CreateModelRequest
	(*CreateModelResponse)(nil),      // 1: fcfs.messages.CreateModelResponse
	(*PredictedGenerationValue)(nil), // 2: fcfs.messages.PredictedGenerationValue
	(*Forecast)(nil),                 // 3: fcfs.messages.Forecast
	(*CreateForecastRequest)(nil),    // 4: fcfs.messages.CreateForecastRequest
	(*CreateForecastsResponse)(nil),  // 5: fcfs.messages.CreateForecastsResponse
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_fcfs_messages_forecast_proto_depIdxs = []int32{
	6, // 0: fcfs.messages.Forecast.init_time_utc:type_name -> google.protobuf.Timestamp
	3, // 1: fcfs.messages.CreateForecastRequest.forecast:type_name -> fcfs.messages.Forecast
	2, // 2: fcfs.messages.CreateForecastRequest.predicted_generation_values:type_name -> fcfs.messages.PredictedGenerationValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fcfs_messages_forecast_proto_init() }
func file_fcfs_messages_forecast_proto_init() {
	if File_fcfs_messages_forecast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fcfs_messages_forecast_proto_rawDesc), len(file_fcfs_messages_forecast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fcfs_messages_forecast_proto_goTypes,
		DependencyIndexes: file_fcfs_messages_forecast_proto_depIdxs,
		MessageInfos:      file_fcfs_messages_forecast_proto_msgTypes,
	}.Build()
	File_fcfs_messages_forecast_proto = out.File
	file_fcfs_messages_forecast_proto_goTypes = nil
	file_fcfs_messages_forecast_proto_depIdxs = nil
}
