// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationType int32

const (
	LocationType_UNKNOWN LocationType = 0
	LocationType_SITE    LocationType = 1
	LocationType_REGION  LocationType = 2
	LocationType_NATION  LocationType = 3
)

// Enum value maps for LocationType.
var (
	LocationType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SITE",
		2: "REGION",
		3: "NATION",
	}
	LocationType_value = map[string]int32{
		"UNKNOWN": 0,
		"SITE":    1,
		"REGION":  2,
		"NATION":  3,
	}
)

func (x LocationType) Enum() *LocationType {
	p := new(LocationType)
	*p = x
	return p
}

func (x LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_api_proto_enumTypes[0].Descriptor()
}

func (LocationType) Type() protoreflect.EnumType {
	return &file_src_proto_api_proto_enumTypes[0]
}

func (x LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationType.Descriptor instead.
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{0}
}

// --- GetPredictedTimeseries --------------------------------------------------------
type GetPredictedTimeseriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationIDs []string `protobuf:"bytes,1,rep,name=locationIDs,proto3" json:"locationIDs,omitempty"`
}

func (x *GetPredictedTimeseriesRequest) Reset() {
	*x = GetPredictedTimeseriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPredictedTimeseriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedTimeseriesRequest) ProtoMessage() {}

func (x *GetPredictedTimeseriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedTimeseriesRequest.ProtoReflect.Descriptor instead.
func (*GetPredictedTimeseriesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetPredictedTimeseriesRequest) GetLocationIDs() []string {
	if x != nil {
		return x.LocationIDs
	}
	return nil
}

type GetPredictedTimeseriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationID string            `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID,omitempty"`
	Yields     []*PredictedYield `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
}

func (x *GetPredictedTimeseriesResponse) Reset() {
	*x = GetPredictedTimeseriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPredictedTimeseriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedTimeseriesResponse) ProtoMessage() {}

func (x *GetPredictedTimeseriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedTimeseriesResponse.ProtoReflect.Descriptor instead.
func (*GetPredictedTimeseriesResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetPredictedTimeseriesResponse) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *GetPredictedTimeseriesResponse) GetYields() []*PredictedYield {
	if x != nil {
		return x.Yields
	}
	return nil
}

type PredictedYield struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YieldKw       int32                      `protobuf:"varint,1,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	TimestampUnix int32                      `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Uncertainty   *PredictedYieldUncertainty `protobuf:"bytes,3,opt,name=uncertainty,proto3" json:"uncertainty,omitempty"`
}

func (x *PredictedYield) Reset() {
	*x = PredictedYield{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictedYield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedYield) ProtoMessage() {}

func (x *PredictedYield) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedYield.ProtoReflect.Descriptor instead.
func (*PredictedYield) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *PredictedYield) GetYieldKw() int32 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

func (x *PredictedYield) GetTimestampUnix() int32 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *PredictedYield) GetUncertainty() *PredictedYieldUncertainty {
	if x != nil {
		return x.Uncertainty
	}
	return nil
}

type PredictedYieldUncertainty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LowerKw int32 `protobuf:"varint,1,opt,name=lower_kw,json=lowerKw,proto3" json:"lower_kw,omitempty"`
	UpperKw int32 `protobuf:"varint,2,opt,name=upper_kw,json=upperKw,proto3" json:"upper_kw,omitempty"`
}

func (x *PredictedYieldUncertainty) Reset() {
	*x = PredictedYieldUncertainty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictedYieldUncertainty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedYieldUncertainty) ProtoMessage() {}

func (x *PredictedYieldUncertainty) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedYieldUncertainty.ProtoReflect.Descriptor instead.
func (*PredictedYieldUncertainty) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *PredictedYieldUncertainty) GetLowerKw() int32 {
	if x != nil {
		return x.LowerKw
	}
	return 0
}

func (x *PredictedYieldUncertainty) GetUpperKw() int32 {
	if x != nil {
		return x.UpperKw
	}
	return 0
}

// --- GetActualTimeseries -----------------------------------------------------------
type GetActualTimeseriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationIDs []string `protobuf:"bytes,1,rep,name=locationIDs,proto3" json:"locationIDs,omitempty"`
}

func (x *GetActualTimeseriesRequest) Reset() {
	*x = GetActualTimeseriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActualTimeseriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActualTimeseriesRequest) ProtoMessage() {}

func (x *GetActualTimeseriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActualTimeseriesRequest.ProtoReflect.Descriptor instead.
func (*GetActualTimeseriesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetActualTimeseriesRequest) GetLocationIDs() []string {
	if x != nil {
		return x.LocationIDs
	}
	return nil
}

type GetActualTimeseriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationID string         `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID,omitempty"`
	Yields     []*ActualYield `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
}

func (x *GetActualTimeseriesResponse) Reset() {
	*x = GetActualTimeseriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActualTimeseriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActualTimeseriesResponse) ProtoMessage() {}

func (x *GetActualTimeseriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActualTimeseriesResponse.ProtoReflect.Descriptor instead.
func (*GetActualTimeseriesResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetActualTimeseriesResponse) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *GetActualTimeseriesResponse) GetYields() []*ActualYield {
	if x != nil {
		return x.Yields
	}
	return nil
}

type ActualYield struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YieldKw       int32 `protobuf:"varint,1,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	TimestampUnix int32 `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

func (x *ActualYield) Reset() {
	*x = ActualYield{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActualYield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualYield) ProtoMessage() {}

func (x *ActualYield) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualYield.ProtoReflect.Descriptor instead.
func (*ActualYield) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *ActualYield) GetYieldKw() int32 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

func (x *ActualYield) GetTimestampUnix() int32 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

// --- GetPredictedCrossSection ------------------------------------------------------
type GetPredictedCrossSectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationIDs   []string `protobuf:"bytes,1,rep,name=locationIDs,proto3" json:"locationIDs,omitempty"`
	TimestampUnix int32    `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

func (x *GetPredictedCrossSectionRequest) Reset() {
	*x = GetPredictedCrossSectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPredictedCrossSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedCrossSectionRequest) ProtoMessage() {}

func (x *GetPredictedCrossSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedCrossSectionRequest.ProtoReflect.Descriptor instead.
func (*GetPredictedCrossSectionRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetPredictedCrossSectionRequest) GetLocationIDs() []string {
	if x != nil {
		return x.LocationIDs
	}
	return nil
}

func (x *GetPredictedCrossSectionRequest) GetTimestampUnix() int32 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type GetPredictedCrossSectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampUnix int64                       `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Yields        []*PredictedYieldAtLocation `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
}

func (x *GetPredictedCrossSectionResponse) Reset() {
	*x = GetPredictedCrossSectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPredictedCrossSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredictedCrossSectionResponse) ProtoMessage() {}

func (x *GetPredictedCrossSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredictedCrossSectionResponse.ProtoReflect.Descriptor instead.
func (*GetPredictedCrossSectionResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetPredictedCrossSectionResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *GetPredictedCrossSectionResponse) GetYields() []*PredictedYieldAtLocation {
	if x != nil {
		return x.Yields
	}
	return nil
}

type PredictedYieldAtLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationID  string                     `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID,omitempty"`
	YieldKw     int32                      `protobuf:"varint,2,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
	Uncertainty *PredictedYieldUncertainty `protobuf:"bytes,3,opt,name=uncertainty,proto3" json:"uncertainty,omitempty"`
}

func (x *PredictedYieldAtLocation) Reset() {
	*x = PredictedYieldAtLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictedYieldAtLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictedYieldAtLocation) ProtoMessage() {}

func (x *PredictedYieldAtLocation) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictedYieldAtLocation.ProtoReflect.Descriptor instead.
func (*PredictedYieldAtLocation) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *PredictedYieldAtLocation) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *PredictedYieldAtLocation) GetYieldKw() int32 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

func (x *PredictedYieldAtLocation) GetUncertainty() *PredictedYieldUncertainty {
	if x != nil {
		return x.Uncertainty
	}
	return nil
}

// --- GetActualCrossSection ---------------------------------------------------------
type GetActualCrossSectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationIDs   []string `protobuf:"bytes,1,rep,name=locationIDs,proto3" json:"locationIDs,omitempty"`
	TimestampUnix int32    `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

func (x *GetActualCrossSectionRequest) Reset() {
	*x = GetActualCrossSectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActualCrossSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActualCrossSectionRequest) ProtoMessage() {}

func (x *GetActualCrossSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActualCrossSectionRequest.ProtoReflect.Descriptor instead.
func (*GetActualCrossSectionRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetActualCrossSectionRequest) GetLocationIDs() []string {
	if x != nil {
		return x.LocationIDs
	}
	return nil
}

func (x *GetActualCrossSectionRequest) GetTimestampUnix() int32 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type GetActualCrossSectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampUnix int64                    `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Yields        []*ActualYieldAtLocation `protobuf:"bytes,2,rep,name=yields,proto3" json:"yields,omitempty"`
}

func (x *GetActualCrossSectionResponse) Reset() {
	*x = GetActualCrossSectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActualCrossSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActualCrossSectionResponse) ProtoMessage() {}

func (x *GetActualCrossSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActualCrossSectionResponse.ProtoReflect.Descriptor instead.
func (*GetActualCrossSectionResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetActualCrossSectionResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *GetActualCrossSectionResponse) GetYields() []*ActualYieldAtLocation {
	if x != nil {
		return x.Yields
	}
	return nil
}

type ActualYieldAtLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationID string `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID,omitempty"`
	YieldKw    int32  `protobuf:"varint,2,opt,name=yield_kw,json=yieldKw,proto3" json:"yield_kw,omitempty"`
}

func (x *ActualYieldAtLocation) Reset() {
	*x = ActualYieldAtLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActualYieldAtLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualYieldAtLocation) ProtoMessage() {}

func (x *ActualYieldAtLocation) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualYieldAtLocation.ProtoReflect.Descriptor instead.
func (*ActualYieldAtLocation) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *ActualYieldAtLocation) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *ActualYieldAtLocation) GetYieldKw() int32 {
	if x != nil {
		return x.YieldKw
	}
	return 0
}

// --- GetLocationMetadata -----------------------------------------------------------
type GetLocationMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationID string `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID,omitempty"`
}

func (x *GetLocationMetadataRequest) Reset() {
	*x = GetLocationMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationMetadataRequest) ProtoMessage() {}

func (x *GetLocationMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetLocationMetadataRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetLocationMetadataRequest) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

type GetLocationMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationID     string                  `protobuf:"bytes,1,opt,name=locationID,proto3" json:"locationID,omitempty"`
	LocationType   LocationType            `protobuf:"varint,2,opt,name=locationType,proto3,enum=api.LocationType" json:"locationType,omitempty"`
	SiteMetadata   *SiteLocationMetadata   `protobuf:"bytes,3,opt,name=siteMetadata,proto3" json:"siteMetadata,omitempty"`
	RegionMetadata *RegionLocationMetadata `protobuf:"bytes,4,opt,name=regionMetadata,proto3" json:"regionMetadata,omitempty"`
	NationMetadata *NationLocationMetadata `protobuf:"bytes,5,opt,name=nationMetadata,proto3" json:"nationMetadata,omitempty"`
}

func (x *GetLocationMetadataResponse) Reset() {
	*x = GetLocationMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationMetadataResponse) ProtoMessage() {}

func (x *GetLocationMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetLocationMetadataResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetLocationMetadataResponse) GetLocationID() string {
	if x != nil {
		return x.LocationID
	}
	return ""
}

func (x *GetLocationMetadataResponse) GetLocationType() LocationType {
	if x != nil {
		return x.LocationType
	}
	return LocationType_UNKNOWN
}

func (x *GetLocationMetadataResponse) GetSiteMetadata() *SiteLocationMetadata {
	if x != nil {
		return x.SiteMetadata
	}
	return nil
}

func (x *GetLocationMetadataResponse) GetRegionMetadata() *RegionLocationMetadata {
	if x != nil {
		return x.RegionMetadata
	}
	return nil
}

func (x *GetLocationMetadataResponse) GetNationMetadata() *NationLocationMetadata {
	if x != nil {
		return x.NationMetadata
	}
	return nil
}

type SiteLocationMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude       float32 `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float32 `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	OrientationDeg int32   `protobuf:"varint,4,opt,name=orientation_deg,json=orientationDeg,proto3" json:"orientation_deg,omitempty"`
	TiltDeg        int32   `protobuf:"varint,5,opt,name=tilt_deg,json=tiltDeg,proto3" json:"tilt_deg,omitempty"`
	CapacityKw     int32   `protobuf:"varint,6,opt,name=capacity_kw,json=capacityKw,proto3" json:"capacity_kw,omitempty"`
}

func (x *SiteLocationMetadata) Reset() {
	*x = SiteLocationMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteLocationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteLocationMetadata) ProtoMessage() {}

func (x *SiteLocationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteLocationMetadata.ProtoReflect.Descriptor instead.
func (*SiteLocationMetadata) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *SiteLocationMetadata) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SiteLocationMetadata) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SiteLocationMetadata) GetOrientationDeg() int32 {
	if x != nil {
		return x.OrientationDeg
	}
	return 0
}

func (x *SiteLocationMetadata) GetTiltDeg() int32 {
	if x != nil {
		return x.TiltDeg
	}
	return 0
}

func (x *SiteLocationMetadata) GetCapacityKw() int32 {
	if x != nil {
		return x.CapacityKw
	}
	return 0
}

type RegionLocationMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionName string `protobuf:"bytes,1,opt,name=regionName,proto3" json:"regionName,omitempty"`
	GspName    string `protobuf:"bytes,2,opt,name=gspName,proto3" json:"gspName,omitempty"`
	CapacityKw string `protobuf:"bytes,3,opt,name=capacity_kw,json=capacityKw,proto3" json:"capacity_kw,omitempty"`
}

func (x *RegionLocationMetadata) Reset() {
	*x = RegionLocationMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionLocationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionLocationMetadata) ProtoMessage() {}

func (x *RegionLocationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionLocationMetadata.ProtoReflect.Descriptor instead.
func (*RegionLocationMetadata) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{16}
}

func (x *RegionLocationMetadata) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *RegionLocationMetadata) GetGspName() string {
	if x != nil {
		return x.GspName
	}
	return ""
}

func (x *RegionLocationMetadata) GetCapacityKw() string {
	if x != nil {
		return x.CapacityKw
	}
	return ""
}

type NationLocationMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NationName string `protobuf:"bytes,1,opt,name=nationName,proto3" json:"nationName,omitempty"`
	CapacityKw string `protobuf:"bytes,2,opt,name=capacity_kw,json=capacityKw,proto3" json:"capacity_kw,omitempty"`
}

func (x *NationLocationMetadata) Reset() {
	*x = NationLocationMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NationLocationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NationLocationMetadata) ProtoMessage() {}

func (x *NationLocationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NationLocationMetadata.ProtoReflect.Descriptor instead.
func (*NationLocationMetadata) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{17}
}

func (x *NationLocationMetadata) GetNationName() string {
	if x != nil {
		return x.NationName
	}
	return ""
}

func (x *NationLocationMetadata) GetCapacityKw() string {
	if x != nil {
		return x.CapacityKw
	}
	return ""
}

var File_src_proto_api_proto protoreflect.FileDescriptor

var file_src_proto_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x41, 0x0a, 0x1d, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x22, 0x6d, 0x0a,
	0x1e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x2b, 0x0a, 0x06, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x59,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x94, 0x01, 0x0a,
	0x0e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6b, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x4b, 0x77, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69,
	0x78, 0x12, 0x40, 0x0a, 0x0b, 0x75, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x55, 0x6e, 0x63, 0x65, 0x72,
	0x74, 0x61, 0x69, 0x6e, 0x74, 0x79, 0x52, 0x0b, 0x75, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x61, 0x69,
	0x6e, 0x74, 0x79, 0x22, 0x51, 0x0a, 0x19, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64,
	0x59, 0x69, 0x65, 0x6c, 0x64, 0x55, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x79,
	0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x6b, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4b, 0x77, 0x12, 0x19, 0x0a, 0x08, 0x75,
	0x70, 0x70, 0x65, 0x72, 0x5f, 0x6b, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x75,
	0x70, 0x70, 0x65, 0x72, 0x4b, 0x77, 0x22, 0x3e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x22, 0x67, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x06, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x74, 0x75,
	0x61, 0x6c, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0x4f, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6b, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x4b, 0x77, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78,
	0x22, 0x6a, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64,
	0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x22, 0x80, 0x01, 0x0a,
	0x20, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x43, 0x72, 0x6f,
	0x73, 0x73, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75,
	0x6e, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x35, 0x0a, 0x06, 0x79, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x41, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0x97, 0x01, 0x0a, 0x18, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x59, 0x69, 0x65,
	0x6c, 0x64, 0x41, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x19, 0x0a, 0x08,
	0x79, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6b, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x79, 0x69, 0x65, 0x6c, 0x64, 0x4b, 0x77, 0x12, 0x40, 0x0a, 0x0b, 0x75, 0x6e, 0x63, 0x65, 0x72,
	0x74, 0x61, 0x69, 0x6e, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x59, 0x69, 0x65, 0x6c,
	0x64, 0x55, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x79, 0x52, 0x0b, 0x75, 0x6e,
	0x63, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x79, 0x22, 0x67, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e,
	0x69, 0x78, 0x22, 0x7a, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x43,
	0x72, 0x6f, 0x73, 0x73, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x32, 0x0a, 0x06, 0x79, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x41, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x52,
	0x0a, 0x15, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x41, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x19, 0x0a, 0x08, 0x79, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x6b, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x79, 0x69, 0x65, 0x6c, 0x64,
	0x4b, 0x77, 0x22, 0x3c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x22, 0xbd, 0x02, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x35, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x73, 0x69, 0x74, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x73, 0x69, 0x74, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x43, 0x0a, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0e, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x43, 0x0a, 0x0e, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x0e, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xb5, 0x01, 0x0a, 0x14, 0x53, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x64, 0x65, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6f, 0x72,
	0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x67, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x69, 0x6c, 0x74, 0x5f, 0x64, 0x65, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x74, 0x69, 0x6c, 0x74, 0x44, 0x65, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x5f, 0x6b, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x61,
	0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x4b, 0x77, 0x22, 0x73, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x73, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x73, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6b, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x4b, 0x77, 0x22, 0x59, 0x0a,
	0x16, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x5f, 0x6b, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61,
	0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x4b, 0x77, 0x2a, 0x3d, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x49, 0x54, 0x45, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4e,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x32, 0xf9, 0x03, 0x0a, 0x09, 0x51, 0x75, 0x61, 0x72,
	0x74, 0x7a, 0x41, 0x50, 0x49, 0x12, 0x65, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x5c, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x74, 0x75, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x60, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x43, 0x72, 0x6f, 0x73,
	0x73, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x43, 0x72, 0x6f, 0x73, 0x73,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65,
	0x64, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x66, 0x69, 0x78,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_api_proto_rawDescOnce sync.Once
	file_src_proto_api_proto_rawDescData = file_src_proto_api_proto_rawDesc
)

func file_src_proto_api_proto_rawDescGZIP() []byte {
	file_src_proto_api_proto_rawDescOnce.Do(func() {
		file_src_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_api_proto_rawDescData)
	})
	return file_src_proto_api_proto_rawDescData
}

var file_src_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_src_proto_api_proto_goTypes = []interface{}{
	(LocationType)(0),                        // 0: api.LocationType
	(*GetPredictedTimeseriesRequest)(nil),    // 1: api.GetPredictedTimeseriesRequest
	(*GetPredictedTimeseriesResponse)(nil),   // 2: api.GetPredictedTimeseriesResponse
	(*PredictedYield)(nil),                   // 3: api.PredictedYield
	(*PredictedYieldUncertainty)(nil),        // 4: api.PredictedYieldUncertainty
	(*GetActualTimeseriesRequest)(nil),       // 5: api.GetActualTimeseriesRequest
	(*GetActualTimeseriesResponse)(nil),      // 6: api.GetActualTimeseriesResponse
	(*ActualYield)(nil),                      // 7: api.ActualYield
	(*GetPredictedCrossSectionRequest)(nil),  // 8: api.GetPredictedCrossSectionRequest
	(*GetPredictedCrossSectionResponse)(nil), // 9: api.GetPredictedCrossSectionResponse
	(*PredictedYieldAtLocation)(nil),         // 10: api.PredictedYieldAtLocation
	(*GetActualCrossSectionRequest)(nil),     // 11: api.GetActualCrossSectionRequest
	(*GetActualCrossSectionResponse)(nil),    // 12: api.GetActualCrossSectionResponse
	(*ActualYieldAtLocation)(nil),            // 13: api.ActualYieldAtLocation
	(*GetLocationMetadataRequest)(nil),       // 14: api.GetLocationMetadataRequest
	(*GetLocationMetadataResponse)(nil),      // 15: api.GetLocationMetadataResponse
	(*SiteLocationMetadata)(nil),             // 16: api.SiteLocationMetadata
	(*RegionLocationMetadata)(nil),           // 17: api.RegionLocationMetadata
	(*NationLocationMetadata)(nil),           // 18: api.NationLocationMetadata
}
var file_src_proto_api_proto_depIdxs = []int32{
	3,  // 0: api.GetPredictedTimeseriesResponse.yields:type_name -> api.PredictedYield
	4,  // 1: api.PredictedYield.uncertainty:type_name -> api.PredictedYieldUncertainty
	7,  // 2: api.GetActualTimeseriesResponse.yields:type_name -> api.ActualYield
	10, // 3: api.GetPredictedCrossSectionResponse.yields:type_name -> api.PredictedYieldAtLocation
	4,  // 4: api.PredictedYieldAtLocation.uncertainty:type_name -> api.PredictedYieldUncertainty
	13, // 5: api.GetActualCrossSectionResponse.yields:type_name -> api.ActualYieldAtLocation
	0,  // 6: api.GetLocationMetadataResponse.locationType:type_name -> api.LocationType
	16, // 7: api.GetLocationMetadataResponse.siteMetadata:type_name -> api.SiteLocationMetadata
	17, // 8: api.GetLocationMetadataResponse.regionMetadata:type_name -> api.RegionLocationMetadata
	18, // 9: api.GetLocationMetadataResponse.nationMetadata:type_name -> api.NationLocationMetadata
	1,  // 10: api.QuartzAPI.GetPredictedTimeseries:input_type -> api.GetPredictedTimeseriesRequest
	5,  // 11: api.QuartzAPI.GetActualTimeseries:input_type -> api.GetActualTimeseriesRequest
	11, // 12: api.QuartzAPI.GetActualCrossSection:input_type -> api.GetActualCrossSectionRequest
	8,  // 13: api.QuartzAPI.GetPredictedCrossSection:input_type -> api.GetPredictedCrossSectionRequest
	14, // 14: api.QuartzAPI.GetLocationMetadata:input_type -> api.GetLocationMetadataRequest
	2,  // 15: api.QuartzAPI.GetPredictedTimeseries:output_type -> api.GetPredictedTimeseriesResponse
	6,  // 16: api.QuartzAPI.GetActualTimeseries:output_type -> api.GetActualTimeseriesResponse
	12, // 17: api.QuartzAPI.GetActualCrossSection:output_type -> api.GetActualCrossSectionResponse
	9,  // 18: api.QuartzAPI.GetPredictedCrossSection:output_type -> api.GetPredictedCrossSectionResponse
	15, // 19: api.QuartzAPI.GetLocationMetadata:output_type -> api.GetLocationMetadataResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_src_proto_api_proto_init() }
func file_src_proto_api_proto_init() {
	if File_src_proto_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPredictedTimeseriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPredictedTimeseriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictedYield); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictedYieldUncertainty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActualTimeseriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActualTimeseriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActualYield); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPredictedCrossSectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPredictedCrossSectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictedYieldAtLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActualCrossSectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActualCrossSectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActualYieldAtLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteLocationMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionLocationMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NationLocationMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_api_proto_goTypes,
		DependencyIndexes: file_src_proto_api_proto_depIdxs,
		EnumInfos:         file_src_proto_api_proto_enumTypes,
		MessageInfos:      file_src_proto_api_proto_msgTypes,
	}.Build()
	File_src_proto_api_proto = out.File
	file_src_proto_api_proto_rawDesc = nil
	file_src_proto_api_proto_goTypes = nil
	file_src_proto_api_proto_depIdxs = nil
}
