#!/bin/sh

echo "Running pre-push checks..."

# Ensure in repo root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT" || exit 1

UNFORMATTED_FILES=$(make lint)
if [ -n "$UNFORMATTED_FILES" ]; then
    echo "ERROR: Linting/fixing reformatted the following files/vendors:"
    for file in $UNFORMATTED_FILES; do
        echo "       - $file"
    done
    echo "       Please stage and commit these changes before pushing."
    echo "       (hint: 'git commit -am \"chore(go): Code formatting and mod tidy\"')"
    exit 1
fi

make gen &> /dev/null
if ! [ $? -eq 0 ]; then
    echo "ERROR: code generation failed. Check above output and fix errors."
    echo "       Then re-run 'make gen'"
    exit 1
fi
