syntax = "proto3";

package ocf.dp;

import "ocf/dp/dp-data.messages.proto";

option go_package = "github.com/openclimatefix/data-platform/internal/protogen/ocf/dp;dp";

service DataPlatformDataService {

  /* GetForecastTimeseries fetches a horizontal slice of predicted data.
   * (i.e. many points in time for a single location). Since individually created forecasts can
   * have overlapping time ranges, identically-timestamped values are discarded, excepting the one
   * with the lowest allowable lead time (horizon).
   */
  rpc GetForecastAsTimeseries(GetForecastAsTimeseriesRequest) returns (GetForecastAsTimeseriesResponse) {}
  /* GetForecastAtTimestamp fetches a vertical slice of predicted data.
   * (i.e. many locations, at a single point in time). This is handy for e.g. display on a map.
   */
  rpc GetForecastAtTimestamp(GetForecastAtTimestampRequest) returns (GetForecastAtTimestampResponse) {}
  /* GetObservationsAsTimeseries fetches a horizontal slice of observed data.
   * (i.e. many points in time, one single location).
   */
  rpc GetObservationsAsTimeseries(GetObservationsAsTimeseriesRequest) returns (GetObservationsAsTimeseriesResponse) {}

  /* GetLocation fetches detailed information about a specific location. */
  rpc GetLocation(GetLocationRequest) returns (GetLocationResponse) {}
  /* CreateLocation registers a new location in which to log or forecast generation. */
  rpc CreateLocation(CreateLocationRequest) returns (CreateLocationResponse) {}
  /* ExtendLocation increases the capacity of a specific location. */
  rpc UpdateLocationCapacity(UpdateLocationCapacityRequest) returns (UpdateLocationCapacityResponse) {}
  /* ListLocations fetches a list of registered locations that match the supplied filters. */
  rpc ListLocations(ListLocationsRequest) returns (ListLocationsResponse) {}

  rpc CreateForecaster(CreateForecasterRequest) returns (CreateForecasterResponse) {}
  rpc UpdateForecaster(UpdateForecasterRequest) returns (UpdateForecasterResponse) {}
  rpc ListForecasters(ListForecastersRequest) returns (ListForecastersResponse) {}

  rpc CreateForecast(CreateForecastRequest) returns (CreateForecastResponse) {}
  rpc GetLatestForecasts(GetLatestForecastsRequest) returns (GetLatestForecastsResponse) {}
  rpc DeleteForecast(DeleteForecastRequest) returns (DeleteForecastResponse) {}

  rpc CreateObserver(CreateObserverRequest) returns (CreateObserverResponse) {}
  rpc ListObservers(ListObserversRequest) returns (ListObserversResponse) {}
  rpc CreateObservations(CreateObservationsRequest) returns (CreateObservationsResponse) {}
  /* GetLatestObservation fetches the most recent observation for a given location and observer. */
  rpc GetLatestObservation(GetLatestObservationRequest) returns (GetLatestObservationResponse) {}

  // --- Analysis ----------------------------------------------------------------

  /* GetLocationsAsGeoJSON fetches a given set of locations as GeoJSON, suitable for display on a
   * map or for integration with GIS software.
   */
  rpc GetLocationsAsGeoJSON(GetLocationsAsGeoJSONRequest) returns (GetLocationsAsGeoJSONResponse) {}
  /* GetWeekAverageDeltas fetches the average delta at the given init time over the past week.
   * This is useful for making adjustments based on recent performance.
   */
  rpc GetWeekAverageDeltas(GetWeekAverageDeltasRequest) returns (GetWeekAverageDeltasResponse) {}

  /* StreamForecastData streams forecast data for a given location, forecasters, and time range.
   * Useful for analytics and performance monitoring.
   */
  rpc StreamForecastData(StreamForecastDataRequest) returns (stream StreamForecastDataResponse) {}

}


