syntax = "proto3";

package ocf.dp;

import "ocf/dp/dp-data.messages.proto";

option go_package = "github.com/openclimatefix/data-platform/internal/protogen/ocf/dp;dp";

service DataPlatformDataService {

  /* GetForecastTimeseries fetches a 1-D horizontal slice of predicted data.
   * These values can either come from a sample of many forecasts; or from one specific forecast. 
   * In the case of the sample, values whose timestamps are shared across overlapping forecasts
   * are cherry-picked based on the lowest allowable lead time (horizon).
   */
  rpc GetForecastAsTimeseries(GetForecastAsTimeseriesRequest) returns (GetForecastAsTimeseriesResponse) {}
  /* GetForecastAtTimestamp fetches a 1-D vertical slice of predicted data.
   * Useful for spatial snapshots at a given time, for instance to display on a map.
   */
  rpc GetForecastAtTimestamp(GetForecastAtTimestampRequest) returns (GetForecastAtTimestampResponse) {}
  /* GetObservationsAsTimeseries fetches a 1-D horizontal slice of observed data.
   * It is the observations analogue of GetForecastAsTimeseries.
   */
  rpc GetObservationsAsTimeseries(GetObservationsAsTimeseriesRequest) returns (GetObservationsAsTimeseriesResponse) {}
  /* GetObservationAtTimestamp fetches a 1-D vertical slice of observation data.
   * It is the observations analogue of GetForecastsAtTimestamp.
   */
  rpc GetObservationsAtTimestamp(GetObservationsAtTimestampRequest) returns (GetObservationsAtTimestampResponse) {}
  /* GetLocation fetches a snapshot of information about a specific location at a point in time. 
   * It can also optionally return the geometry of the location.
   */
  rpc GetLocation(GetLocationRequest) returns (GetLocationResponse) {}
  /* GetLocationAsTimeseries fetches the history of a location across a given time window. */
  rpc GetLocationAsTimeseries(GetLocationAsTimeseriesRequest) returns (GetLocationAsTimeseriesResponse) {}
  /* CreateLocation registers a new location in which to log or forecast generation. */
  rpc CreateLocation(CreateLocationRequest) returns (CreateLocationResponse) {}
  /* UpdateLocation modifies various attributes associated with a given location. */
  rpc UpdateLocation(UpdateLocationRequest) returns (UpdateLocationResponse) {}
  /* ListLocations fetches a list of registered locations that match the supplied filters. */
  rpc ListLocations(ListLocationsRequest) returns (ListLocationsResponse) {}
  /* CreateForecaster registers a new forecaster. 
   * A forecaster is a producer of predicted values. Forecasters are differentiated by their name and version. */
  rpc CreateForecaster(CreateForecasterRequest) returns (CreateForecasterResponse) {}
  /* UpdateForecaster modifies the version of an existing forecaster. */
  rpc UpdateForecaster(UpdateForecasterRequest) returns (UpdateForecasterResponse) {}
  /* ListForecasters fetches a list of registered forecasters that match the supplied filters. */
  rpc ListForecasters(ListForecastersRequest) returns (ListForecastersResponse) {}

  /* CreateForecast saves a timeseries of predicted values from a given forecaster. */
  rpc CreateForecast(CreateForecastRequest) returns (CreateForecastResponse) {}
  /* GetLatestForecasts fetches metadata for the most recently produced forecasts. */
  rpc GetLatestForecasts(GetLatestForecastsRequest) returns (GetLatestForecastsResponse) {}
  /* DeleteForecast removes a series of forecast values from the database. */
  rpc DeleteForecast(DeleteForecastRequest) returns (DeleteForecastResponse) {}

  /* CreateObserver registers a new observer. 
   * An observer is a producer of observed, or measured, values. */
  rpc CreateObserver(CreateObserverRequest) returns (CreateObserverResponse) {}
  /* ListObservers fetches a list of registered observers that match the supplied filters. */
  rpc ListObservers(ListObserversRequest) returns (ListObserversResponse) {}
  /* CreateObservations saves a timeseries of observed values from a given observer. */
  rpc CreateObservations(CreateObservationsRequest) returns (CreateObservationsResponse) {}
  /* GetLatestObservation fetches the most recent observation for a given location and observer. */
  rpc GetLatestObservations(GetLatestObservationsRequest) returns (GetLatestObservationsResponse) {}

  // --- Analysis ----------------------------------------------------------------

  /* GetLocationsAsGeoJSON fetches a given set of locations as GeoJSON, suitable for display on a
   * map or for integration with GIS software.
   */
  rpc GetLocationsAsGeoJSON(GetLocationsAsGeoJSONRequest) returns (GetLocationsAsGeoJSONResponse) {}
  /* GetWeekAverageDeltas fetches the average delta at the given init time over the past week.
   * This is useful for making adjustments based on recent performance.
   */
  rpc GetWeekAverageDeltas(GetWeekAverageDeltasRequest) returns (GetWeekAverageDeltasResponse) {}

  /* StreamForecastData streams forecast data for a given location, forecasters, and time range.
   * Useful for analytics and performance monitoring.
   */
  rpc StreamForecastData(StreamForecastDataRequest) returns (stream StreamForecastDataResponse) {}

}


