// Common messages for the Quartz API

syntax = "proto3";

package ocf.dp;

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";
import "buf/validate/validate.proto";
import "ocf/dp/dp.rules.proto";
import "ocf/dp/dp.common.proto";

option go_package = "github.com/openclimatefix/data-platform/internal/protogen/ocf/dp;dp";

// --- Common message types ----------------------------------------------------------------------
message Forecaster {
  string forecaster_name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_forecaster_name) = true
  ];
  /* The version of the forecaster to use. If not specified, the latest version will be used.
   */
  string forecaster_version = 2;
}

message TimeWindow {
  /* The start of the time window, inclusive.
   * Cannot be more than 7 days before end_timestamp_utc, nor more than 1 month in the future.
   */
  google.protobuf.Timestamp start_timestamp_utc = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).timestamp = { gt: { seconds: 112000000} },
    (buf.validate.field).cel = {
      id: "timestamp_not_too_far_in_future"
      message: "start_timestamp_utc cannot be more than 30 days in the future"
      expression: "this <= now + duration('720h')"
    }
  ];
  /* The end of the time window, inclusive.
   * Cannot be more than 7 days after start_timestamp_utc.
   */
  google.protobuf.Timestamp end_timestamp_utc = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).timestamp.gt = { seconds: 112000000}
  ];

  option (buf.validate.message).cel = {
    id: "maximum_window_size"
    message: "window size must not exceed 7 days"
    expression: "this.end_timestamp_utc - this.start_timestamp_utc <= duration('604800s')"
  };
  option (buf.validate.message).cel = {
    id: "start_before_end"
    message: "start_timestamp_utc must be before end_timestamp_utc"
    expression: "this.start_timestamp_utc <= this.end_timestamp_utc"
  };
}

// --- Requests and Responses --------------------------------------------------------

message GetForecastAsTimeseriesRequest {
  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];

  uint32 horizon_mins = 3;
  TimeWindow time_window = 4 [
    (buf.validate.field).required = true
  ];
  Forecaster forecaster = 5 [
    (buf.validate.field).required = true
  ];
  /* The time to search backwards from to find forecasts.
   * If not specified, the current time will be used.
   */
  optional google.protobuf.Timestamp pivot_timestamp_utc = 6 [
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];
}

message GetForecastAsTimeseriesResponse {
  message Value {
    google.protobuf.Timestamp target_timestamp_utc = 1;
    float p50_value_fraction = 2;
    uint64 effective_capacity_watts = 3;
    google.protobuf.Timestamp initialization_timestamp_utc = 4;
    google.protobuf.Timestamp created_timestamp_utc = 5;
    map<string, float> other_statistics_fractions = 6;
    google.protobuf.Struct metadata = 7;
  }

  string location_uuid = 1;
  string location_name = 2;
  repeated GetForecastAsTimeseriesResponse.Value values = 3;
}


message GetObservationsAsTimeseriesRequest {
  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  string observer_name = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_observer_name) = true
  ];
  EnergySource energy_source = 3 [
    (buf.validate.field).required = true 
  ];
  TimeWindow time_window = 4 [
    (buf.validate.field).required = true
  ];
}

message GetObservationsAsTimeseriesResponse {
  message Value {
    google.protobuf.Timestamp timestamp_utc = 1;
    float value_fraction = 2;
    uint64 effective_capacity_watts = 3;
  }

  string location_uuid = 1;
  repeated Value values = 2;
}


message GetForecastAtTimestampRequest {
  repeated string location_uuids = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 1000,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      string: {uuid: true}
    }
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  /* The time to fetch predicted yields for.
   * If not specified, the current time will be used.
   */
  optional google.protobuf.Timestamp timestamp_utc = 3 [
    (buf.validate.field).timestamp = { gt: { seconds: 112000000} },
    (buf.validate.field).cel = {
      id: "timestamp_not_too_far_in_future"
      message: "timestamp_utc cannot be more than 30 days in the future"
      expression: "this <= now + duration('720h')"
    }
  ];
  Forecaster forecaster = 4 [
    (buf.validate.field).required = true
  ];
}

message GetForecastAtTimestampResponse {
  message Value {
    string location_uuid = 1;
    string location_name = 2;
    float value_fraction = 3;
    uint64 effective_capacity_watts = 4;
    LatLng latlng = 5;
    google.protobuf.Struct metadata = 6;
    google.protobuf.Timestamp initialization_timestamp_utc = 7;
    google.protobuf.Timestamp created_timestamp_utc = 8;
  }

  google.protobuf.Timestamp timestamp_utc = 1;
  repeated Value values = 2;
}


message GetObservationsAtTimestampRequest {
  repeated string location_uuids = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 1000,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      string: {uuid: true}
    }
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  string observer_name = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_observer_name) = true
  ];
  /* The time to fetch observations for.
   * If not specified, the current time will be used.
   */
  optional google.protobuf.Timestamp timestamp_utc = 4 [
    (buf.validate.field).timestamp = { gt: { seconds: 112000000} }
  ];
}

message GetObservationsAtTimestampResponse {
  message Value {
    string location_uuid = 1;
    float value_fraction = 2;
    uint64 effective_capacity_watts = 3;
    LatLng latlng = 4;
    google.protobuf.Struct metadata = 5;
  }

  google.protobuf.Timestamp timestamp_utc = 1;
  repeated Value values = 2;
}


message GetLatestForecastsRequest {
  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  /* The time to search backwards from to find the 'latest' forecast.
   * If not specified, the current time will be used.
   */
  optional google.protobuf.Timestamp pivot_timestamp_utc = 3 [
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];
}

message GetLatestForecastsResponse {
  message Forecast {
    google.protobuf.Timestamp initialization_timestamp_utc = 1;
    google.protobuf.Timestamp created_timestamp_utc = 2;
    Forecaster forecaster = 3;
    string location_uuid = 4;
    google.protobuf.Struct metadata = 5;
  }

  repeated GetLatestForecastsResponse.Forecast forecasts = 1;
}


message CreateForecasterRequest {
  string name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_forecaster_name) = true
  ];
  string version = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_forecaster_name) = true
  ];
}

message CreateForecasterResponse {
  Forecaster forecaster = 1;
}


message UpdateForecasterRequest {
  string name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_forecaster_name) = true
  ];
  string new_version = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_forecaster_name) = true
  ];
}

message UpdateForecasterResponse {
  Forecaster forecaster = 1;
}


message ListForecastersRequest {
  // Optional filter to only return forecasters from a given set.
  // If empty, all forecasters will be returned.
  repeated string forecaster_names_filter = 1 [
    (buf.validate.field).repeated.max_items = 100,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      string: {min_len: 2, max_len: 100},
    }
  ];
  // If true, only the latest version of each forecaster will be returned.
  bool latest_versions_only = 2;
}

message ListForecastersResponse {
  repeated Forecaster forecasters = 1;
}


message CreateForecastRequest {
  message ForecastValue {
    uint32 horizon_mins = 1;
    float p50_fraction = 2 [
      (buf.validate.field).float.gte = 0,
      (buf.validate.field).float.lte = 1.1,
      (buf.validate.field).float.finite = true
    ];
    // Struct for storing additional statistics like p10, p90, mean etc.
    map<string, float> other_statistics_fractions = 3 [
      (buf.validate.field).map.min_pairs = 0,
      (buf.validate.field).map.max_pairs = 20,
      (buf.validate.field).map.values = {
        float: {
          gte: 0.0,
          lte: 1.1,
          finite: true
        }
      }
    ];
    optional google.protobuf.Struct metadata = 4;
  }

  Forecaster forecaster = 1 [
    (buf.validate.field).required = true
  ];

  string location_uuid = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];

  EnergySource energy_source = 3 [
    (buf.validate.field).required = true
  ];

  google.protobuf.Timestamp init_time_utc = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];

  repeated CreateForecastRequest.ForecastValue values = 5 [
    (buf.validate.field).repeated.min_items = 2,
    (buf.validate.field).repeated.max_items = 5000
  ];

  optional google.protobuf.Struct metadata = 6;

  //option (buf.validate.message).cel = {
  //  id: "forecast.values.monotonic_horizons"
  //  message: "Forecast horizon values must be monotonically increasing"
  //  expression:
  //    "this.values.all(i, v, "
  //      "i == 0 || ("
  //        "v.horizon_mins > this.values[i-1].horizon_mins && "
  //        "(v.horizon_mins - this.values[i-1].horizon_mins == this.values[1].horizon_mins - this.values[0].horizon_mins)"
  //      ")"
  //    ")"
  //};
}

message CreateForecastResponse {
  string forecast_uuid = 1;
}


message DeleteForecastRequest {
  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  Forecaster forecaster = 3 [
    (buf.validate.field).required = true
  ];
  google.protobuf.Timestamp init_time_utc = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];
}

message DeleteForecastResponse {}


message CreateLocationRequest {
  string location_name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_location_name) = true
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  // A geometry string in Well-Known-Text (WKT) format.
  // Geometry type must be POINT, POLYGON, or MULTIPOLYGON, must have 2 dimensions,
  // and must be in the EPSG:4326 coordinate system (longitude/latitude).
  string geometry_wkt = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_geometry) = true,
    (buf.validate.field).string.example = "POLYGON ((-0.127 51.507, -0.127 51.507, -0.127 51.507, -0.127 51.507))"
  ];
  // The effective capacity of the location in watts.
  // This refers to the useable capacity for generation, not the installed capacity.
  // If tracking of installed capacity is required, this should be stored in metadata.
  uint64 effective_capacity_watts = 4 [
    (buf.validate.field).required = true
  ];
  LocationType location_type = 5 [
    (buf.validate.field).required = true 
  ];
  optional google.protobuf.Struct metadata = 6;
  // The UTC time from which this location is considered valid. Leave empty to use current time.
  optional google.protobuf.Timestamp valid_from_utc = 7 [
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];
  // Optional latitude/longitude to associate with the location.
  // Defaults to the centroid of the geometry if not provided. Not required for Point geometries.
  optional LatLng associated_latlng = 8;

  option (buf.validate.message).cel = {
    id: "latlng_invalid_for_point"
    message: "latlng must not be provided for Point geometries"
    expression:
      "this.geometry_wkt.startsWith('POINT') ? !has(this.associated_latlng) : true"
  };
}

message CreateLocationResponse {
  string location_uuid = 1;
  string location_name = 2;
  uint64 effective_capacity_watts = 3;
}


message GetLocationRequest {
  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  EnergySource energy_source = 2[
    (buf.validate.field).required = true 
  ];
  // If true, the geometry_wkb field will be included in the response.
  // This may be very big, so only include if necessary.
  bool include_geometry = 3;
  // The UTC time the data should be valid for. Leave empty to use current time.
  optional google.protobuf.Timestamp pivot_timestamp_utc = 4 [
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];
}

message GetLocationResponse {
  string location_uuid = 1;
  string location_name = 2;
  LatLng latlng = 3;
  uint64 effective_capacity_watts = 4;
  google.protobuf.Struct metadata = 5;
  optional bytes geometry_wkb = 6;
}

message UpdateLocationRequest {
  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  // The new name for the location.
  optional string new_location_name = 3 [
    (buf.validate.field).string.(valid_location_name) = true
  ];
  optional uint64 new_effective_capacity_watts = 4 [
    (buf.validate.field).uint64.gte = 0
  ];
  // The new metadata object to set for the location.
  // Note that this will replace any existing metadata, so be sure to include existing fields where
  // needed.
  optional google.protobuf.Struct new_metadata = 5;
  // The UTC time from which this name is considered valid. Leave empty to use current time.
  optional google.protobuf.Timestamp valid_from_utc = 6 [
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];

  // Ensure one of the updatable fields is set.
  option (buf.validate.message).cel = {
    id: "at_least_one_field"
    message: "at least one updatable field must be set"
    expression: 
        "has(this.new_location_name) "
        "|| has(this.new_effective_capacity_watts) "
        "|| has(this.new_metadata) ? true : false" 
  };
}

message UpdateLocationResponse {
  string location_uuid = 1;
  string location_name = 2;
  uint64 effective_capacity_watts = 3;
}

message GetLocationsAsGeoJSONRequest {
  repeated string location_uuids = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 1000,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      string: {uuid:  true}
    } 
  ];
  /* If true, the GeoJSON will not be simplified.
   * Defaults to false if not set to reduce response size.
   */
  bool unsimplified = 2;
}

message GetLocationsAsGeoJSONResponse {
  string geojson = 1;
}


message CreateObservationsRequest {
  message Value {
    google.protobuf.Timestamp timestamp_utc = 1 [
      (buf.validate.field).required = true,
      (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
    ];
    uint64 value_watts = 2 [
      (buf.validate.field).uint64.gte = 0
    ];
  }

  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  string observer_name = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_observer_name) = true
  ];
  repeated CreateObservationsRequest.Value values = 4 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 10000
  ];
}

message CreateObservationsResponse {}


message GetLatestObservationsRequest {
  repeated string location_uuids = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 100,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      string: {uuid: true}
    }
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  string observer_name = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_observer_name) = true
  ];
  /* The time to search backwards from to find the 'latest' observation.
   * If not specified, the current time will be used.
   */
  optional google.protobuf.Timestamp pivot_timestamp_utc = 4 [
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];
}

message GetLatestObservationsResponse {
  message Observation {
    string location_uuid = 1;
    google.protobuf.Timestamp timestamp_utc = 2;
    float value_fraction = 3;
    uint64 effective_capacity_watts = 4;
  }

  repeated GetLatestObservationsResponse.Observation observations = 1;
}


message CreateObserverRequest {
  string name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_observer_name) = true
  ];
}

message CreateObserverResponse {
  string observer_uuid = 1;
  string observer_name = 2;
}


message ListObserversRequest {
  // Optional filter to only return observers from a given set.
  // If empty, all observers will be returned.
  repeated string observer_names_filter = 1 [
    (buf.validate.field).repeated.max_items = 100,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
        string: {min_len: 2, max_len: 100},
    }
  ];
}

message ListObserversResponse {
  message ObserverSummary {
    string observer_uuid = 1;
    string observer_name = 2;
  }

  repeated ObserverSummary observers = 1;
}


message GetWeekAverageDeltasRequest {
  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  /* The characteristic time to detrmine averages for.
   * The time component specifies the initialization time,
   * and the date component is to define the end of the seven-day period
   * over which to average.
   */
  google.protobuf.Timestamp pivot_timestamp_utc = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
  ];
  Forecaster forecaster = 4 [
    (buf.validate.field).required = true
  ];
  string observer_name = 5 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.(valid_observer_name) = true
  ];
}

message GetWeekAverageDeltasResponse {
  message AverageDelta {
    uint32 horizon_mins = 1;
    float delta_fraction = 2;
    uint64 effective_capacity_watts = 3;
  }

  repeated AverageDelta deltas = 1;
  /* The initialisation time that was compared across the week.
   * Formatted as HH:MM, e.g. "12:00"
   */
  string init_time_of_day = 2 [
    (buf.validate.field).string.pattern = "^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$"
  ];
}

message ListLocationsRequest {
  // Optional filter to only return locations of a specific energy source.
  optional EnergySource energy_source_filter = 1;
  // Optional filter to only return locations of a specific location type.
  optional LocationType location_type_filter = 2;
  // Optional filter to only return locations from a given set.
  repeated string location_uuids_filter = 3 [
    (buf.validate.field).repeated.max_items = 1000,
    (buf.validate.field).repeated.items = {
      string: {uuid: true}
    }
  ];
  // Optional filter to only return locations belonging to a specific user.
  optional string user_oauth_id_filter = 4 [
    (buf.validate.field).string.max_len = 128
  ];
  // Optional filter to only return locations for which the user has a specific permission.
  optional Permission permission_filter = 5;
  // Optional filter to only return locations enclosed within a specific location.
  optional string enclosing_location_uuid_filter = 6 [
    (buf.validate.field).string.uuid = true
  ];
  // Optional filter to only return locations that enclose a specific location.
  optional string enclosed_location_uuid_filter = 7 [
    (buf.validate.field).string.uuid = true
  ];


  option (buf.validate.message).cel = {
    id: "enclosing_and_enclosed_mutually_exclusive"
    message: "enclosing_location_uuid_filter and enclosed_location_uuid_filter cannot both be set"
    expression:
      "!(has(this.enclosing_location_uuid_filter) && has(this.enclosed_location_uuid_filter))"
  };
}

message ListLocationsResponse {
  message LocationSummary {
    string location_uuid = 1;
    string location_name = 2;
    EnergySource energy_source = 3;
    LocationType location_type = 4;
    uint64 effective_capacity_watts = 5;
    LatLng latlng = 6;
    google.protobuf.Struct metadata = 7;
  }

  repeated LocationSummary locations = 1;
}


message StreamForecastDataRequest {
  message TimeWindow {
    /* The start of the time window, inclusive.
     * Cannot be more than 31 days before end_timestamp_utc.
     */
    google.protobuf.Timestamp start_timestamp_utc = 1 [
      (buf.validate.field).required = true,
      (buf.validate.field).timestamp = { gt: { seconds: 112000000}, lt_now: true }
    ];
    /* The end of the time window, inclusive.
     * Cannot be more than 31 days after start_timestamp_utc.
     */
    google.protobuf.Timestamp end_timestamp_utc = 2 [
      (buf.validate.field).required = true,
      (buf.validate.field).timestamp.gt = { seconds: 112000000}
    ];

    option (buf.validate.message).cel = {
      id: "maximum_window_size"
      message: "window size must not exceed 31 days"
      expression: "this.end_timestamp_utc - this.start_timestamp_utc <= duration('2678400s')"
    };
    option (buf.validate.message).cel = {
      id: "start_before_end"
      message: "start_timestamp_utc must be before end_timestamp_utc"
      expression: "this.start_timestamp_utc <= this.end_timestamp_utc"
    };
  }

  string location_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
  EnergySource energy_source = 2 [
    (buf.validate.field).required = true 
  ];
  StreamForecastDataRequest.TimeWindow time_window = 3 [
    (buf.validate.field).required = true
  ];
  repeated Forecaster forecasters = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 20
  ];
  bool include_metadata = 5;
}

message StreamForecastDataResponse {
  google.protobuf.Timestamp init_timestamp = 1;
  string location_uuid = 2;
  string forecaster_fullname = 3;
  uint32 horizon_mins = 4;
  float p50_fraction = 5;
  map<string, float> other_statistics_fractions = 6;
  google.protobuf.Timestamp created_timestamp_utc = 7;
  uint64 effective_capacity_watts = 8;
  map<string, string> metadata = 9;
}

