FROM postgres:16-bookworm

RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-16-partman \
    && apt-cache showpkg postgresql-16-postgis-3 \
    && apt-get install -y --no-install-recommends \
        postgresql-16-postgis-3 \
        postgresql-16-postgis-3-scripts \
    && rm -rf /var/lib/apt/lists/*

COPY init_postgis.sh /docker-entrypoint-initdb.d/10_init_postgis.sh
COPY init_partman_bgw.sh /docker-entrypoint-initdb.d/99_init_partman_bgw.sh
