FROM postgres:18-trixie

RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-18-partman \
    && apt-cache showpkg postgresql-18-postgis-3 \
    && apt-get install -y --no-install-recommends \
        postgresql-18-postgis-3 \
        postgresql-18-postgis-3-scripts \
    && apt-get install -y --no-install-recommends postgresql-18-cron \
    && rm -rf /var/lib/apt/lists/*

CMD [ "postgres","-c","shared_preload_libraries=pg_cron" ]
