// @generated by protobuf-ts 2.9.6 with parameter output_javascript
// @generated from protobuf file "fcfs/service.proto" (package "fcfs", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.6 with parameter output_javascript
// @generated from protobuf file "fcfs/service.proto" (package "fcfs", syntax proto3)
// tslint:disable
import { CreatePredictedGenerationValuesResponse } from "./messages/forecast";
import { CreatePredictedGenerationValuesRequest } from "./messages/forecast";
import { CreateForecastsResponse } from "./messages/forecast";
import { CreateForecastsRequest } from "./messages/forecast";
import { CreateModelResponse } from "./messages/forecast";
import { CreateModelRequest } from "./messages/forecast";
import { GetLocationResponse } from "./messages/location";
import { GetLocationRequest } from "./messages/location";
import { CreateGspRequest } from "./messages/location";
import { CreateLocationResponse } from "./messages/location";
import { CreateSiteRequest } from "./messages/location";
import { GetPredictedCrossSectionResponse } from "./messages/quartzui";
import { GetPredictedCrossSectionRequest } from "./messages/quartzui";
import { GetActualCrossSectionResponse } from "./messages/quartzui";
import { GetActualCrossSectionRequest } from "./messages/quartzui";
import { GetActualTimeseriesResponse } from "./messages/quartzui";
import { GetActualTimeseriesRequest } from "./messages/quartzui";
import { GetPredictedTimeseriesResponse } from "./messages/quartzui";
import { GetPredictedTimeseriesRequest } from "./messages/quartzui";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service fcfs.QuartzAPI
 */
export const QuartzAPI = new ServiceType("fcfs.QuartzAPI", [
    { name: "GetPredictedTimeseries", serverStreaming: true, options: {}, I: GetPredictedTimeseriesRequest, O: GetPredictedTimeseriesResponse },
    { name: "GetActualTimeseries", serverStreaming: true, options: {}, I: GetActualTimeseriesRequest, O: GetActualTimeseriesResponse },
    { name: "GetActualCrossSection", options: {}, I: GetActualCrossSectionRequest, O: GetActualCrossSectionResponse },
    { name: "GetPredictedCrossSection", options: {}, I: GetPredictedCrossSectionRequest, O: GetPredictedCrossSectionResponse },
    { name: "CreateSolarSite", options: {}, I: CreateSiteRequest, O: CreateLocationResponse },
    { name: "CreateSolarGsp", options: {}, I: CreateGspRequest, O: CreateLocationResponse },
    { name: "GetSolarSite", options: {}, I: GetLocationRequest, O: GetLocationResponse },
    { name: "GetSolarGsp", options: {}, I: GetLocationRequest, O: GetLocationResponse },
    { name: "CreateModel", options: {}, I: CreateModelRequest, O: CreateModelResponse },
    { name: "CreateSolarForecasts", options: {}, I: CreateForecastsRequest, O: CreateForecastsResponse },
    { name: "CreatePredictedGenerationValuesRequest", options: {}, I: CreatePredictedGenerationValuesRequest, O: CreatePredictedGenerationValuesResponse }
]);
