version: '3'

tasks:
  generate-proto-go:
    desc: "Generate Go gRPC client and server interfaces."
    aliases: ["gen-pro-go"]
    cmds:
      - |
        protoc \
          --go_out=. \
          --go_opt=paths=source_relative \
          --go-grpc_out=. \
          --go-grpc_opt=paths=source_relative \
          src/proto/api.proto
