name: Benchmark
on:
  push:
    tags: ['v*']
    branches: ['main']
    paths-ignore: ['README.md', 'examples/**']
  pull_request_target:
    branches: ['main']
    paths-ignore: ['README.md', 'examples/**']

jobs:
  bench:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Set up Protoc compiler
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0

      - name: Generate code
        run: go install tool && make gen

      - name: Restore PR base branch benchmarks
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: 'bench-main.txt'
          # Use base SHA for pull requests to ensure cache is reused
          key: ${{ runner.os }}-bench-${{ (github.event.pull_request.base.sha != github.event.after) && github.event.pull_request.base.sha || github.event.after }}

      - name: Run benchmarks
        id: bench
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          make bench > bench-${BRANCH_NAME##*/}.txt
          PAYLOAD=$(cat bench-${BRANCH_NAME##*/}.txt)
          echo "result<<EOF"$'\n'"$PAYLOAD"$'\n'EOF >> "$GITHUB_OUTPUT"
          cat bench-${BRANCH_NAME##*/}.txt

      - name: Compare benchmarks
        id: bench-diff
        if: github.event_name == 'pull_request_target'
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          go tool benchstat bench-main.txt bench-${BRANCH_NAME##*/}.txt >> bench-diff.txt
          PAYLOAD=$(cat bench-diff.txt)
          echo "diff<<EOF"$'\n'"$PAYLOAD"$'\n'EOF >> "$GITHUB_OUTPUT"

      - name: Write results to PR comment
        if: github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@d2ad0de260ae8b0235ce059e63f2949ba9e05943 # v2.9.3
        with:
          header: bench
          message: |
            ### Benchmark Results
            <details><summary>Benchmark results</summary>

            ```
            ${{ steps.bench.outputs.result }}
            ```
            </details>

            <details><summary>Benchmark vs base branch</summary>

            ```
            ${{ steps.bench.outputs.diff }}
            ```
            </details>
