name: Unit Test

on:
  push:
    branches-ignore: ['main']
    paths-ignore: ['README.md', 'examples/**']

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Set up Protoc compiler
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
      
      - name: Check code generation
        run: go install tool && make gen

      - name: Check linting
        run: |
          OUTPUT=$(make lint)
          if [ -n "$OUTPUT" ]; then
            echo "Linting errors found:"
            echo "$OUTPUT"
            exit 1
          else
            echo "No linting errors found."
          fi

      - name: Run unit tests
        run: make test

      - name: Test Summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: "unit-tests.xml"
          output: "test-summary.md"
        if: always()

      - name: Get associated PR
        id: findpr
        uses: jwalton/gh-find-current-pr@89ee5799558265a1e0e31fab792ebb4ee91c016b # v1.3.3
      
      - name: Write results to PR comment
        if: success() && steps.findpr.outputs.number
        uses: marocchino/sticky-pull-request-comment@d2ad0de260ae8b0235ce059e63f2949ba9e05943 # v2.9.3
        with:
          number: ${{ steps.findpr.outputs.pr }}
          header: unit-test
          path: test-summary.md

