name: Unit Test

on:
  push:
    branches-ignore: ['main']
    paths-ignore: ['README.md', 'examples/**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go mod download

      - name: Check linting
        run: |
          make lint >> $GITHUB_STEP_SUMMARY
          if [ -n "$(cat $GITHUB_STEP_SUMMARY)" ]; then
            exit 1
          fi

      - name: Run unit tests
        run: make test

      - name: Test Summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: "unit-tests.xml"
          show: "all"
        if: always()

