name: Unit Test

on:
  push:
    branches-ignore: ['main']
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: api/go.mod
          cache: true
          cache-dependency-path: api/go.sum

      - name: Install dependencies
        run: cd api && go mod download

      - name: Run unit tests
        run: cd api && go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format testname

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "api/unit-tests.xml"
        if: always()

